#!/bin/bash
# Copyright (c) 2026 anonysec
# SPDX-License-Identifier: MIT
#
# ══════════════════════════════════════════════════════════════════════
#  OVNode — OpenVPN Node Agent Installer v4
#
#  One installer, four ways to run it:
#
#    humans, interactive :  bash <(curl -Ls URL)
#    humans, one-liner   :  bash <(curl -Ls URL) install -y --tls selfsigned
#    automation / AI     :  bash <(curl -Ls URL) install -y --json \
#                               --api-key "$KEY" --vpn-ports 1194,443
#    config via env      :  OVN_API_KEY=$KEY OVN_TLS=selfsigned \
#                               bash <(curl -Ls URL) install -y --json
#
#  Commands : install (default) | update | uninstall | status | help
#  Modes    : native (systemd, default) | --docker (container runs the
#             agent AND OpenVPN, supervised — see docker/entrypoint.sh)
#
#  Machine interface (for scripts and AI agents):
#    --json        exactly one JSON object on stdout, all logs on stderr
#    -y / --yes    never prompts (also implied by --json or no TTY)
#    env overrides OVN_* mirror every flag (CLI wins over env)
#    exit codes    0 ok · 1 error · 2 usage · 3 already installed ·
#                  4 not installed
#
#  What install does: agent (uv venv + systemd unit, or docker compose),
#  OpenVPN scaffolding (PKI + server.conf are generated by the agent on
#  first boot), TLS for the API, IP forwarding + NAT masquerade,
#  multi-port redirects, firewall openings, log rotation, health check.
# ══════════════════════════════════════════════════════════════════════

set -Eeuo pipefail

# ── Constants ──────────────────────────────────────────────────────────
VERSION="4.0"
REPO="anonysec/OVNode"
# OVN_APP_DIR override exists for hermetic tests: status/uninstall probes
# below must be runnable on machines that already host a node (like CI
# sandboxes and dev boxes) without seeing the real install.
APP_DIR="${OVN_APP_DIR:-/opt/ovnode}"
DATA_BASE="/var/lib/ovnode"
OPENVPN_ROOT="/etc/openvpn"
DEFAULT_PORT=2083
DEFAULT_VPN=1194
SYSTEMD_SERVICE="ovnode.service"
NAT_SERVICE="ovnode-nat.service"
NAT_SCRIPT="/usr/local/sbin/ovnode-nat.sh"
NAT_CONF="/etc/default/ovnode-nat"
SYSCTL_CONF="/etc/sysctl.d/99-ovnode.conf"
LOGROTATE_CONF="/etc/logrotate.d/ovnode"

# Exit codes (documented in --help; stable for automation)
EX_OK=0 EX_ERROR=1 EX_USAGE=2 EX_ALREADY=3 EX_NOTINSTALLED=4

# ── Settings (env defaults OVN_*, overridden by CLI flags) ─────────────
ACTION="install"
PORT="${OVN_PORT:-}"
API_KEY="${OVN_API_KEY:-}"
VPN_PORTS="${OVN_VPN_PORTS:-}"
NODE_NAME="${OVN_NAME:-}"
BRANCH="${OVN_BRANCH:-main}"
TLS_METHOD="${OVN_TLS:-none}"
TLS_DOMAIN="${OVN_TLS_DOMAIN:-}"
TLS_KEY="${OVN_TLS_KEY:-}"
TLS_CERT="${OVN_TLS_CERT:-}"
DOCKER="${OVN_DOCKER:-0}"
IPV6="${OVN_IPV6:-0}"
NO_NAT="${OVN_NO_NAT:-0}"
YES="${OVN_YES:-0}"
PURGE="${OVN_PURGE:-0}"
JSON="${OVN_JSON:-0}"
QUIET="${OVN_QUIET:-0}"
# Derived by validate_input:
VPN_PORT="" EXTRA_PORTS=""

# ── Output ─────────────────────────────────────────────────────────────
# Contract: ALL human-readable output goes to stderr. stdout carries
# exactly one JSON object in --json mode and nothing otherwise — so
# `RESULT=$(installer ... --json)` is always parseable.
NC=$'\033[0m'; B=$'\033[1m'
WH=$'\033[97m'; GR=$'\033[32m'; RD=$'\033[31m'
YL=$'\033[33m'; CY=$'\033[36m'; GY=$'\033[90m'
[[ -t 2 ]] || { NC=''; B=''; WH=''; GR=''; RD=''; YL=''; CY=''; GY=''; }

line()  { [[ "$QUIET" -eq 1 ]] || echo -e "  $1" >&2; }
step()  { line "${GR}  ✓${NC} $1"; }
info()  { line "${CY}  →${NC} $1"; }
warn()  { line "${YL}  ⚠${NC} $1"; }
field() { [[ "$QUIET" -eq 1 ]] || printf "  ${GY}%-18s${NC} %s\n" "$1" "$2" >&2; }
sep()   { line "${GY}$(printf '%.0s─' {1..56})${NC}"; }

json_escape() {  # minimal escaper for values we emit
    local s="${1//\\/\\\\}"; s="${s//\"/\\\"}"
    s="${s//$'\n'/ }"; s="${s//$'\t'/ }"
    printf '%s' "$s"
}

# die <message> [exit-code]  — single error path, JSON-aware.
die() {
    local msg="$1" code="${2:-$EX_ERROR}"
    echo -e "\n  ${RD}Error:${NC} $msg\n" >&2
    if [[ "$JSON" -eq 1 ]]; then
        printf '{"ok":false,"action":"%s","error":"%s","exit_code":%d}\n' \
            "$(json_escape "$ACTION")" "$(json_escape "$msg")" "$code"
    fi
    exit "$code"
}

trap 'echo -e "\n  ${RD}Interrupted.${NC}" >&2; exit 130' INT TERM
trap 'warn "Command failed near line $LINENO (running: ${BASH_COMMAND:0:80})"' ERR

is_tty() { [[ -t 0 && -t 2 ]]; }
# Spinners/prompts only for interactive humans; plain logs otherwise.
fancy()  { is_tty && [[ "$QUIET" -eq 0 && "$JSON" -eq 0 ]]; }

spinner() {
    local msg="$1" pid=$2 chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' i=0 rc=0
    while kill -0 "$pid" 2>/dev/null; do
        printf "\r  ${CY}%s${NC} %-46s" "${chars:$((i%9)):1}" "$msg" >&2
        sleep 0.1; i=$(( i + 1 ))
    done
    wait "$pid" 2>/dev/null || rc=$?
    printf "\r\033[K" >&2
    [[ $rc -eq 0 ]] && step "$msg" || { line "${RD}  ✗${NC} $msg"; return $rc; }
}

# run <label> <cmd...> — required step: spinner on a TTY, plain log lines
# in automation. Fails the install with a clear message on error.
run() {
    local label="$1"; shift
    if fancy; then
        ( "$@" ) >/dev/null 2>&1 &
        spinner "$label" $! || die "Step failed: $label"
    else
        "$@" >/dev/null 2>&1 || die "Step failed: $label"
        step "$label"
    fi
}

# try_run <label> <cmd...> — best-effort step: warns instead of dying.
try_run() {
    local label="$1"; shift
    if fancy; then
        ( "$@" ) >/dev/null 2>&1 &
        spinner "$label" $! || { warn "$label — failed (continuing)"; return 1; }
    else
        if "$@" >/dev/null 2>&1; then step "$label"; else
            warn "$label — failed (continuing)"; return 1
        fi
    fi
}

ask() {
    local label="$1" default="$2" hidden="${3:-}" val=""
    if is_tty && [[ "$YES" -eq 0 ]]; then
        printf "  ${WH}%-24s${NC} ${GY}[%s]${NC} : " "$label" "$default" >&2
        if [[ "$hidden" == "h" ]]; then read -rs val; printf "\n" >&2; else read -r val; fi
    fi
    echo "${val:-$default}"
}

confirm() {
    [[ "$YES" -eq 1 ]] && return 0
    is_tty || return 0
    printf "  %s [${GR}Y${NC}/n] : " "$1" >&2
    read -r c
    [[ ! "$c" =~ ^[Nn]$ ]]
}

# ── OS / package manager ───────────────────────────────────────────────
OS_ID="" OS_NAME="" PKG_INSTALL="" PKG_UPDATE=""

detect_os() {
    [[ -f /etc/os-release ]] || die "Unsupported OS — no /etc/os-release found."
    # shellcheck disable=SC1091
    . /etc/os-release
    OS_ID="${ID:-}"; OS_NAME="${PRETTY_NAME:-$OS_ID}"
    case "$OS_ID" in
        debian|ubuntu)      PKG_UPDATE="apt-get update -qq";  PKG_INSTALL="apt-get install -y -qq" ;;
        rhel|centos|rocky|almalinux|fedora)
            if command -v dnf >/dev/null 2>&1; then
                PKG_UPDATE="dnf -q makecache"; PKG_INSTALL="dnf install -y -q"
            else
                PKG_UPDATE="yum -q makecache"; PKG_INSTALL="yum install -y -q"
            fi ;;
        arch)               PKG_UPDATE="pacman -Sy --noconfirm"; PKG_INSTALL="pacman -S --noconfirm" ;;
        alpine)             PKG_UPDATE="apk update -q";          PKG_INSTALL="apk add -q" ;;
        *) die "Unsupported distribution: ${OS_ID:-unknown}" ;;
    esac
}

pkg_install() {
    info "Installing: $*"
    $PKG_UPDATE >/dev/null 2>&1 || true
    $PKG_INSTALL "$@" >/dev/null 2>&1 || die "Failed to install: $*"
}

has_systemd() { command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; }

# ── Help / args ────────────────────────────────────────────────────────
show_help() {
    cat << 'EOF' >&2
  OVNode installer — native (systemd) or Docker, human or machine.

  Usage:
    bash <(curl -Ls URL) [command] [flags]

  Commands:
    install             Install OVNode (default when omitted)
    update              Pull latest source and restart (with backup)
    uninstall           Remove OVNode (data kept unless --purge)
    status              Report install state (respects --json)
    help                This help

  Flags (every flag has an OVN_* env equivalent; CLI wins):
    --port PORT         Sync API port                    [OVN_PORT, 2083]
    --api-key KEY       API key, min 16 chars            [OVN_API_KEY, generated]
    --vpn-ports LIST    OpenVPN ports, comma separated   [OVN_VPN_PORTS, 1194]
                        First = listener; the rest are redirected to it and
                        included in every .ovpn (client failover).
    --vpn-port PORT     Shorthand for a single port
    --name NAME         Node name                        [OVN_NAME, node-1]
    --branch BRANCH     Source branch                    [OVN_BRANCH, main]
    --tls METHOD        letsencrypt | letsencrypt-ip | selfsigned |
                        custom | none                    [OVN_TLS, none]
    --tls-domain DOM    Domain/IP for Let's Encrypt      [OVN_TLS_DOMAIN]
    --tls-key  FILE     Private key (--tls custom)       [OVN_TLS_KEY]
    --tls-cert FILE     Certificate (--tls custom)       [OVN_TLS_CERT]
    --docker            Deploy in Docker (container runs agent + OpenVPN,
                        host networking)                 [OVN_DOCKER=1]
    --ipv6              Enable IPv6 on the VPN           [OVN_IPV6=1]
    --no-nat            Skip forwarding/NAT/redirects    [OVN_NO_NAT=1]
    --purge             With uninstall: remove data too  [OVN_PURGE=1]
    --yes | -y          Never prompt, accept defaults    [OVN_YES=1]
    --json              Machine output: one JSON object on stdout, logs on
                        stderr; implies --yes            [OVN_JSON=1]
    --quiet | -q        Suppress progress logs (errors still shown)
    --help | -h         This help

  Exit codes:
    0 success · 1 error · 2 usage error · 3 already installed ·
    4 not installed

  Automation example (safe to parse):
    RESULT=$(bash install.sh install --json --tls selfsigned) || exit
    KEY=$(echo "$RESULT" | jq -r .api_key)
    BUNDLE=$(echo "$RESULT" | jq -r .bundle)  # paste into panel: Nodes → Add Node
EOF
    exit "$EX_OK"
}

parse_args() {
    local need2='[[ $# -ge 2 ]] || die "$1 needs a value" "$EX_USAGE"'
    while [[ $# -gt 0 ]]; do
        case "$1" in
            install)      ACTION="install"; shift ;;
            update)       ACTION="update"; shift ;;
            uninstall|--uninstall) ACTION="uninstall"; shift ;;
            status)       ACTION="status"; shift ;;
            help|--help|-h) show_help ;;
            --port)       eval "$need2"; PORT="$2"; shift 2 ;;
            --api-key)    eval "$need2"; API_KEY="$2"; shift 2 ;;
            --vpn-ports|--vpn-port) eval "$need2"; VPN_PORTS="$2"; shift 2 ;;
            --name)       eval "$need2"; NODE_NAME="$2"; shift 2 ;;
            --branch)     eval "$need2"; BRANCH="$2"; shift 2 ;;
            --tls)        eval "$need2"; TLS_METHOD="$2"; shift 2 ;;
            --tls-domain) eval "$need2"; TLS_DOMAIN="$2"; shift 2 ;;
            --tls-key)    eval "$need2"; TLS_KEY="$2"; shift 2 ;;
            --tls-cert)   eval "$need2"; TLS_CERT="$2"; shift 2 ;;
            --docker)     DOCKER=1; shift ;;
            --ipv6)       IPV6=1; shift ;;
            --no-nat)     NO_NAT=1; shift ;;
            --yes|-y)     YES=1; shift ;;
            --purge)      PURGE=1; shift ;;
            --json)       JSON=1; YES=1; shift ;;
            --quiet|-q)   QUIET=1; shift ;;
            *)            die "Unknown option: $1 (--help for usage)" "$EX_USAGE" ;;
        esac
    done
    # No TTY = nobody to answer prompts: behave as --yes.
    is_tty || YES=1
}

# ── Validation ─────────────────────────────────────────────────────────
is_port() { [[ "$1" =~ ^[0-9]+$ ]] && (( $1 >= 1 && $1 <= 65535 )); }

# Splits VPN_PORTS ("1194,443,8443") into VPN_PORT (primary listener) and
# EXTRA_PORTS (comma separated, redirected to the primary).
parse_vpn_ports() {
    local raw="${VPN_PORTS:-$DEFAULT_VPN}" seen=" " port
    VPN_PORT="" EXTRA_PORTS=""
    IFS=',' read -ra _ports <<< "${raw// /}"
    for port in "${_ports[@]}"; do
        [[ -z "$port" ]] && continue
        is_port "$port" || die "Invalid OpenVPN port: '$port'" "$EX_USAGE"
        [[ "$seen" == *" $port "* ]] && continue
        seen+="$port "
        if [[ -z "$VPN_PORT" ]]; then
            VPN_PORT="$port"
        else
            EXTRA_PORTS="${EXTRA_PORTS:+$EXTRA_PORTS,}$port"
        fi
    done
    [[ -n "$VPN_PORT" ]] || die "At least one OpenVPN port is required" "$EX_USAGE"
}

validate_input() {
    is_port "$PORT" || die "Invalid service port: '$PORT'" "$EX_USAGE"
    parse_vpn_ports
    [[ "$VPN_PORT" == "$PORT" ]] && die "OpenVPN port and service port must differ" "$EX_USAGE"
    [[ -n "$NODE_NAME" ]] || NODE_NAME="node-1"
    [[ "$NODE_NAME" =~ ^[A-Za-z0-9_-]{1,64}$ ]] || die "Invalid node name" "$EX_USAGE"
    [[ -n "$API_KEY" ]] || die "API key is required (--api-key / OVN_API_KEY; interactive installs generate one)" "$EX_USAGE"
    [[ ${#API_KEY} -ge 16 ]] || die "API key must be at least 16 characters (openssl rand -hex 32)" "$EX_USAGE"
    case "$TLS_METHOD" in
        letsencrypt|letsencrypt-ip|selfsigned|custom|none) ;;
        *) die "Invalid TLS method: '$TLS_METHOD'" "$EX_USAGE" ;;
    esac
    if [[ "$TLS_METHOD" == "letsencrypt" || "$TLS_METHOD" == "letsencrypt-ip" ]]; then
        [[ -n "$TLS_DOMAIN" ]] || die "--tls-domain is required for Let's Encrypt" "$EX_USAGE"
    fi
    if [[ "$TLS_METHOD" == "custom" ]]; then
        [[ -f "$TLS_KEY" && -f "$TLS_CERT" ]] || die "Custom TLS key/cert files not found" "$EX_USAGE"
    fi
}

port_in_use() { ss -ltn 2>/dev/null | awk -v p=":${1}$" '$4 ~ p {exit 0} END {exit 1}'; }

find_free_port() {
    local port="${1:-$DEFAULT_PORT}"
    while port_in_use "$port"; do ((port++)); done
    echo "$port"
}

vpn_ports_label() {
    if [[ -n "$EXTRA_PORTS" ]]; then
        echo "${VPN_PORT} (+ redirects: ${EXTRA_PORTS})"
    else
        echo "$VPN_PORT"
    fi
}

primary_ip() { hostname -I 2>/dev/null | awk '{print $1}'; }

# ── Toolchain ──────────────────────────────────────────────────────────
UV_BIN=""
ensure_uv() {
    if command -v uv >/dev/null 2>&1; then
        UV_BIN="$(command -v uv)"; step "uv found: $UV_BIN"; return
    fi
    info "Installing uv (Python package manager)..."
    curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null 2>&1 || \
        python3 -m pip install --quiet uv >/dev/null 2>&1 || \
        die "Could not install uv."
    UV_BIN="$(command -v uv 2>/dev/null || true)"
    [[ -n "$UV_BIN" ]] || UV_BIN="$HOME/.local/bin/uv"
    [[ -x "$UV_BIN" ]] || die "uv not found after install"
    step "uv installed: $UV_BIN"
}

# Reproducible dependency install: the lockfile pins exact versions.
# Fall back to a fresh resolve only when the lock cannot be honored.
uv_sync() {
    "$UV_BIN" sync --frozen --no-dev --quiet 2>/dev/null \
        || "$UV_BIN" sync --no-dev --quiet
}

# ── Backups ────────────────────────────────────────────────────────────
backup_dir() {
    local src="$1" label="$2"
    [[ -d "$src" ]] || return 0
    mkdir -p /var/backups
    local stamp; stamp="$(date +%Y%m%d-%H%M%S)"
    local base; base="$(basename "$src")"
    local file="/var/backups/${label}-${base}-${stamp}.tar.gz"
    if tar -czf "$file" -C "$(dirname "$src")" "$base" 2>/dev/null; then
        step "Backup saved: $file"
    else
        warn "Backup failed for $src — continuing anyway"
    fi
}

# ── TLS ────────────────────────────────────────────────────────────────
generate_selfsigned() {
    mkdir -p /etc/ssl/self-signed
    local cn; cn="$(primary_ip)"
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout /etc/ssl/self-signed/privkey.pem \
        -out /etc/ssl/self-signed/fullchain.pem \
        -subj "/C=US/ST=Local/L=Local/O=OVNode/CN=${cn:-ovnode}" >/dev/null 2>&1
    TLS_KEY="/etc/ssl/self-signed/privkey.pem"
    TLS_CERT="/etc/ssl/self-signed/fullchain.pem"
    step "Self-signed certificate generated"
}

ensure_acme() {
    if [[ ! -x "$HOME/.acme.sh/acme.sh" ]]; then
        run "Installing acme.sh" bash -c 'curl -s https://get.acme.sh | sh'
    fi
}

issue_letsencrypt() {
    local domain="$1" is_ip="$2"
    ensure_acme
    local email="acme-$(openssl rand -hex 4)@example.com"
    local outdir="/etc/letsencrypt/$domain"
    mkdir -p "$outdir"

    if [[ -f "$outdir/fullchain.pem" ]]; then
        local expiry days_left=0
        expiry="$(openssl x509 -enddate -noout -in "$outdir/fullchain.pem" 2>/dev/null | cut -d= -f2)"
        days_left=$(( ($(date -d "$expiry" +%s 2>/dev/null || echo 0) - $(date +%s)) / 86400 ))
        if (( days_left > 7 )); then
            step "Existing certificate valid for ${days_left} more days"
            TLS_KEY="$outdir/privkey.pem"; TLS_CERT="$outdir/fullchain.pem"
            return 0
        fi
        warn "Certificate expires soon (${days_left}d) — renewing..."
    fi

    local extra_args=()
    if [[ "$is_ip" == "1" ]]; then extra_args=(--certificate-profile shortlived --days 6); fi

    "$HOME/.acme.sh/acme.sh" --issue -d "$domain" --standalone "${extra_args[@]}" \
        --accountemail "$email" >/dev/null 2>&1 \
        || die "Failed to issue Let's Encrypt certificate for $domain (is port 80 free and the domain pointed here?)"

    "$HOME/.acme.sh/acme.sh" --install-cert -d "$domain" \
        --key-file "$outdir/privkey.pem" \
        --fullchain-file "$outdir/fullchain.pem" \
        --reloadcmd "systemctl restart $SYSTEMD_SERVICE >/dev/null 2>&1 || true" >/dev/null 2>&1 \
        || die "Failed to install certificate to $outdir"
    TLS_KEY="$outdir/privkey.pem"; TLS_CERT="$outdir/fullchain.pem"
    step "Certificate installed to $outdir"
}

setup_tls() {
    case "$TLS_METHOD" in
        none) ;;
        selfsigned)     generate_selfsigned ;;
        letsencrypt)    issue_letsencrypt "$TLS_DOMAIN" "0" ;;
        letsencrypt-ip) issue_letsencrypt "$TLS_DOMAIN" "1" ;;
        custom)
            local out="/etc/letsencrypt/${TLS_DOMAIN:-node}"
            mkdir -p "$out"
            cp "$TLS_KEY" "$out/privkey.pem"
            cp "$TLS_CERT" "$out/fullchain.pem"
            TLS_KEY="$out/privkey.pem"; TLS_CERT="$out/fullchain.pem"
            step "Custom certificate installed to $out"
            ;;
    esac
}

# ── Forwarding / NAT / multi-port redirects ────────────────────────────
# IP forwarding is a host sysctl in BOTH modes (a container usually cannot
# write /proc/sys). The iptables rules live in one idempotent script owned
# by a oneshot systemd unit — native mode only; in Docker the entrypoint
# applies the equivalent rules itself via CAP_NET_ADMIN.
write_sysctl() {
    cat > "$SYSCTL_CONF" << 'SYSCTL'
# OVNode: allow OpenVPN clients to route through this host
net.ipv4.ip_forward = 1
SYSCTL
    if [[ "$IPV6" -eq 1 ]]; then
        echo "net.ipv6.conf.all.forwarding = 1" >> "$SYSCTL_CONF"
    fi
    sysctl -p "$SYSCTL_CONF" >/dev/null 2>&1 || true
    step "IP forwarding enabled ($SYSCTL_CONF)"
}

write_nat_files() {
    cat > "$NAT_CONF" << CONF
# OVNode NAT configuration (managed by install.sh)
VPN_PRIMARY_PORT=${VPN_PORT}
VPN_EXTRA_PORTS=${EXTRA_PORTS}
CONF

    cat > "$NAT_SCRIPT" << 'NAT'
#!/bin/bash
# OVNode NAT: masquerade VPN client traffic through the default uplink and
# redirect the extra VPN ports to the OpenVPN listener. Idempotent.
# Usage: ovnode-nat.sh [apply|cleanup]
set -u
CONF="/etc/default/ovnode-nat"
VPN_PRIMARY_PORT="" VPN_EXTRA_PORTS=""
# shellcheck disable=SC1090
[[ -f "$CONF" ]] && . "$CONF"

rule() {  # rule <add|del> <table> <chain> <args...>
    local op="$1" table="$2" chain="$3"; shift 3
    if [[ "$op" == "add" ]]; then
        iptables -t "$table" -C "$chain" "$@" 2>/dev/null || iptables -t "$table" -A "$chain" "$@"
    else
        iptables -t "$table" -D "$chain" "$@" 2>/dev/null || true
    fi
}

each_redirect() {  # each_redirect <add|del>
    local op="$1" port proto
    [[ -n "$VPN_PRIMARY_PORT" && -n "$VPN_EXTRA_PORTS" ]] || return 0
    for port in ${VPN_EXTRA_PORTS//,/ }; do
        for proto in tcp udp; do
            rule "$op" nat PREROUTING -p "$proto" --dport "$port" \
                -j REDIRECT --to-ports "$VPN_PRIMARY_PORT"
        done
    done
}

IFACE="$(ip route show default 2>/dev/null | awk '{print $5; exit}')"

case "${1:-apply}" in
    apply)
        if [[ -z "$IFACE" ]]; then echo "ovnode-nat: no default interface found" >&2; exit 1; fi
        rule add nat POSTROUTING -o "$IFACE" -j MASQUERADE
        each_redirect add
        ;;
    cleanup)
        [[ -n "$IFACE" ]] && rule del nat POSTROUTING -o "$IFACE" -j MASQUERADE
        each_redirect del
        ;;
    *) echo "usage: $0 [apply|cleanup]" >&2; exit 2 ;;
esac
NAT
    chmod +x "$NAT_SCRIPT"

    cat > "/etc/systemd/system/$NAT_SERVICE" << UNIT
[Unit]
Description=OVNode NAT (masquerade + VPN port redirects)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$NAT_SCRIPT apply
ExecStop=$NAT_SCRIPT cleanup

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload >/dev/null 2>&1
    systemctl enable "$NAT_SERVICE" >/dev/null 2>&1
    if systemctl restart "$NAT_SERVICE" >/dev/null 2>&1; then
        if [[ -n "$EXTRA_PORTS" ]]; then
            step "NAT enabled, ports ${EXTRA_PORTS} → ${VPN_PORT}"
        else
            step "NAT enabled"
        fi
    else
        warn "Could not start NAT service — VPN clients may not route traffic"
    fi
}

setup_nat() {
    if [[ "$NO_NAT" -eq 1 ]]; then info "Skipping NAT setup (--no-nat)"; return 0; fi
    write_sysctl
    if [[ "$DOCKER" -eq 1 ]]; then
        info "Docker mode: NAT/redirect rules are applied inside the container (CAP_NET_ADMIN)"
        return 0
    fi
    if ! command -v iptables >/dev/null 2>&1; then
        pkg_install iptables iproute2
    fi
    write_nat_files
}

# ── Log rotation ───────────────────────────────────────────────────────
# server.conf uses `log-append openvpn.log`, which grows without bound and
# will eventually fill a small VPS disk (killing OpenVPN with it). The
# agent log rotates itself; the OpenVPN log needs logrotate. copytruncate
# is used because OpenVPN keeps the file descriptor open.
setup_logrotate() {
    if ! command -v logrotate >/dev/null 2>&1; then
        if [[ -n "$PKG_INSTALL" ]]; then
            pkg_install logrotate
        else
            warn "logrotate not found — install it so openvpn.log gets rotated"
            return 0
        fi
    fi
    cat > "$LOGROTATE_CONF" << ROTATE
${OPENVPN_ROOT}/server/openvpn.log {
    size 10M
    rotate 3
    compress
    missingok
    notifempty
    copytruncate
}
ROTATE
    step "Log rotation configured ($LOGROTATE_CONF)"
}

# ── OpenVPN scaffolding ────────────────────────────────────────────────
ensure_openvpn_dirs() {
    mkdir -p "$OPENVPN_ROOT/server" "$OPENVPN_ROOT/ccd" \
             "$OPENVPN_ROOT/ovnode/users" "$OPENVPN_ROOT/ovnode/sessions" \
             "$OPENVPN_ROOT/ovnode/scripts" "$OPENVPN_ROOT/ovnode/usage"
    # Some distros (Arch) lack the "nogroup" group that the generated
    # server.conf references — create it so OpenVPN can start.
    getent group nogroup >/dev/null 2>&1 || groupadd -r nogroup 2>/dev/null || true
    # The tun device is required; try to load the kernel module if missing.
    if [[ ! -e /dev/net/tun ]]; then
        mkdir -p /dev/net
        modprobe tun 2>/dev/null || true
        mknod /dev/net/tun c 10 200 2>/dev/null || true
        chmod 600 /dev/net/tun 2>/dev/null || true
    fi
    if [[ -e /dev/net/tun ]]; then
        step "OpenVPN directories ready ($OPENVPN_ROOT), /dev/net/tun present"
    else
        warn "/dev/net/tun is missing — OpenVPN cannot start (Docker: mount it, bare-metal: modprobe tun)"
    fi
}

start_openvpn_service() {
    # The agent generates server.conf + PKI on first boot; enable/start the
    # systemd instance that reads it.
    if has_systemd; then
        systemctl enable openvpn-server@server >/dev/null 2>&1 || true
        systemctl restart openvpn-server@server >/dev/null 2>&1 && \
            step "OpenVPN server service started" || \
            warn "Could not start openvpn-server@server — check: journalctl -u openvpn-server@server -n 50"
    elif command -v rc-service >/dev/null 2>&1; then
        rc-update add openvpn default >/dev/null 2>&1 || true
        rc-service openvpn start >/dev/null 2>&1 && step "OpenVPN started (OpenRC)" || warn "Start OpenVPN manually"
    else
        warn "No init system detected — start OpenVPN manually: openvpn --config $OPENVPN_ROOT/server/server.conf"
    fi
}

# ── Firewall ───────────────────────────────────────────────────────────
# Every VPN port is opened for BOTH protocols: the panel can switch the
# node between udp and tcp at runtime, and the extra-port redirects always
# cover both.
open_firewall_ports() {
    local vpn_all="$VPN_PORT ${EXTRA_PORTS//,/ }" p
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw allow "$PORT/tcp" >/dev/null 2>&1
        for p in $vpn_all; do
            ufw allow "$p/udp" >/dev/null 2>&1
            ufw allow "$p/tcp" >/dev/null 2>&1
        done
        step "UFW: allowed $PORT/tcp + VPN port(s) ${vpn_all// /, }"
    elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
        firewall-cmd --permanent --add-port="$PORT/tcp" >/dev/null 2>&1
        for p in $vpn_all; do
            firewall-cmd --permanent --add-port="$p/udp" >/dev/null 2>&1
            firewall-cmd --permanent --add-port="$p/tcp" >/dev/null 2>&1
        done
        firewall-cmd --reload >/dev/null 2>&1
        step "firewalld: allowed $PORT/tcp + VPN port(s) ${vpn_all// /, }"
    fi
}

# ── Systemd unit ───────────────────────────────────────────────────────
write_systemd_unit() {
    # ExecStart runs the venv interpreter directly: no uv resolution at
    # boot, one fewer process, faster restarts, lower RAM.
    cat > "/etc/systemd/system/$SYSTEMD_SERVICE" << UNIT
[Unit]
Description=OVNode OpenVPN Node Agent (${NODE_NAME})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=${APP_DIR}
Environment="PATH=${APP_DIR}/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
EnvironmentFile=${APP_DIR}/.env
ExecStart=${APP_DIR}/.venv/bin/python ${APP_DIR}/main.py
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload >/dev/null 2>&1
    systemctl enable "$SYSTEMD_SERVICE" >/dev/null 2>&1
    step "systemd unit written: /etc/systemd/system/$SYSTEMD_SERVICE"
}

wait_health() {
    local url="$1" tries="${2:-30}" i
    for i in $(seq 1 "$tries"); do
        curl -fsSk -o /dev/null --max-time 3 "$url" 2>/dev/null && return 0
        sleep 1
    done
    return 1
}

# ── Source / environment ───────────────────────────────────────────────
fetch_source() {
    if command -v git >/dev/null 2>&1; then
        run "Cloning repository ($BRANCH)" \
            git clone --depth 1 --branch "$BRANCH" "https://github.com/${REPO}.git" "$APP_DIR"
    else
        run "Downloading source tarball" \
            curl -sSLo /tmp/ovn.tar.gz "https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz"
        mkdir -p "$APP_DIR"
        tar -xzf /tmp/ovn.tar.gz --strip-components=1 -C "$APP_DIR" >/dev/null 2>&1 || die "Extract failed"
        rm -f /tmp/ovn.tar.gz
    fi
}

write_env() {
    # Note: TUNNEL_ADDRESS is intentionally NOT written here — the node's
    # pydantic Settings rejects extra env fields, and the panel pushes the
    # tunnel address via /sync/config when the node is added/updated.
    cat > "$APP_DIR/.env" << EOF
NODE_NAME=${NODE_NAME}
DATA_DIR=${DATA_BASE}/${NODE_NAME}
SERVICE_PORT=${PORT}
API_KEY=${API_KEY}
OPENVPN_PORT=${VPN_PORT}
TLS_METHOD=${TLS_METHOD}
$( if [[ -n "$EXTRA_PORTS" ]]; then echo "OVNODE_EXTRA_PORTS=${EXTRA_PORTS}"; fi )
$( if [[ "$IPV6" -eq 1 ]]; then echo "OVNODE_ENABLE_IPV6=1"; fi )
$( if [[ -n "$TLS_KEY" ]]; then echo "SSL_KEYFILE=${TLS_KEY}"; fi )
$( if [[ -n "$TLS_CERT" ]]; then echo "SSL_CERTFILE=${TLS_CERT}"; fi )
EOF
    chmod 600 "$APP_DIR/.env"
    step ".env written"
}

# ── Docker ─────────────────────────────────────────────────────────────
compose_file() { echo "$DATA_BASE/${NODE_NAME:-node-1}/docker-compose.yml"; }

ensure_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        info "Installing Docker Engine..."
        if [[ "$PKG_INSTALL" == apt* ]]; then
            $PKG_UPDATE >/dev/null 2>&1 || true
            $PKG_INSTALL docker.io >/dev/null 2>&1 \
                || $PKG_INSTALL docker-ce >/dev/null 2>&1 \
                || die "Could not install Docker via apt. Install manually: https://docs.docker.com/engine/install/"
        else
            pkg_install docker docker-compose-plugin >/dev/null 2>&1 || pkg_install docker
        fi
        command -v docker >/dev/null 2>&1 || die "Docker binary not found"
    fi
    docker compose version >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1 \
        || die "Docker Compose v2 is required (docker compose plugin)"
    step "Docker present"
}

setup_docker() {
    ensure_docker

    # The image's entrypoint runs OpenVPN inside the container; the host
    # only needs the tun module loaded and the device node present.
    modprobe tun >/dev/null 2>&1 || true
    if [[ ! -c /dev/net/tun ]]; then
        mkdir -p /dev/net && mknod /dev/net/tun c 10 200 2>/dev/null || true
    fi
    [[ -c /dev/net/tun ]] || warn "/dev/net/tun missing — the VPN cannot start until the tun module is available"

    local compose; compose="$(compose_file)"
    mkdir -p "$DATA_BASE/$NODE_NAME"

    # TLS material lives on host paths (letsencrypt/self-signed/custom) —
    # mount them read-only or the agent cannot serve HTTPS. Let's Encrypt
    # needs the whole tree: live/ contains symlinks into archive/.
    local tls_mounts="" d f
    for f in "$TLS_KEY" "$TLS_CERT"; do
        [[ -n "$f" ]] || continue
        case "$f" in
            /etc/letsencrypt/*) d="/etc/letsencrypt" ;;
            *) d="$(dirname "$f")" ;;
        esac
        [[ "$tls_mounts" == *"- ${d}:${d}:ro"* ]] || tls_mounts+="      - ${d}:${d}:ro"$'\n'
    done

    cat > "$compose" << COMPOSE
services:
  ovnode:
    build:
      context: ${APP_DIR}
      dockerfile: Dockerfile
    container_name: ovnode-${NODE_NAME}
    restart: unless-stopped
    network_mode: host
    environment:
      SERVICE_PORT: ${PORT}
      API_KEY: ${API_KEY}
      OPENVPN_PORT: ${VPN_PORT}
      TLS_METHOD: ${TLS_METHOD}
      OVNODE_OPENVPN_ROOT: /etc/openvpn
$( if [[ -n "$EXTRA_PORTS" ]]; then echo "      OVNODE_EXTRA_PORTS: \"${EXTRA_PORTS}\""; fi )
$( if [[ "$IPV6" -eq 1 ]]; then echo "      OVNODE_ENABLE_IPV6: 1"; fi )
$( [[ -n "$TLS_KEY" ]] && echo "      SSL_KEYFILE: ${TLS_KEY}" )
$( [[ -n "$TLS_CERT" ]] && echo "      SSL_CERTFILE: ${TLS_CERT}" )
    volumes:
      - ${OPENVPN_ROOT}:/etc/openvpn
      - ${DATA_BASE}/${NODE_NAME}:/app/data
      - /dev/net/tun:/dev/net/tun
$( [[ -n "$tls_mounts" ]] && printf '%s' "$tls_mounts" )
    cap_add:
      - NET_ADMIN
    logging:
      options:
        max-size: "5m"
        max-file: "3"
COMPOSE
    # The compose file embeds the API key — keep it root-only, like .env.
    chmod 600 "$compose"
    step "Compose file written: $compose"

    run "Building and starting container (first build takes a while)" \
        docker compose -f "$compose" up -d --build
}

# ── JSON result ────────────────────────────────────────────────────────
# emit_result <ok> <action> [key value]... — values are emitted as strings
# except numbers/booleans, detected by shape. One line, stdout only.
emit_result() {
    [[ "$JSON" -eq 1 ]] || return 0
    local ok="$1" action="$2"; shift 2
    local out="{\"ok\":$ok,\"action\":\"$(json_escape "$action")\",\"installer_version\":\"$VERSION\""
    while [[ $# -ge 2 ]]; do
        local k="$1" v="$2"; shift 2
        if [[ "$v" =~ ^-?[0-9]+$ || "$v" == "true" || "$v" == "false" || "$v" == "null" || "$v" == \[*\] ]]; then
            out+=",\"$k\":$v"
        else
            out+=",\"$k\":\"$(json_escape "$v")\""
        fi
    done
    printf '%s}\n' "$out"
}

vpn_ports_json() {
    local out="[$VPN_PORT" p
    for p in ${EXTRA_PORTS//,/ }; do out+=",$p"; done
    printf '%s]' "$out"
}

# ── Install ────────────────────────────────────────────────────────────
do_install() {
    check_root
    check_deps
    [[ "$DOCKER" -eq 1 ]] || ensure_uv

    sep; info "Downloading OVNode ($BRANCH)..."
    fetch_source

    if [[ "$DOCKER" -eq 0 ]]; then
        cd "$APP_DIR"
        run "Installing Python dependencies" uv_sync
    fi

    setup_tls
    write_env

    local scheme="http"
    [[ "$TLS_METHOD" != "none" ]] && scheme="https"
    local host; host="$(primary_ip)"

    mkdir -p "$DATA_BASE/$NODE_NAME"
    ensure_openvpn_dirs

    if [[ "$DOCKER" -eq 1 ]]; then
        setup_docker
    else
        if ! has_systemd; then
            warn "systemd not found — start the agent manually: cd $APP_DIR && .venv/bin/python main.py"
        else
            write_systemd_unit
            run "Starting node agent service" systemctl restart "$SYSTEMD_SERVICE"
        fi
    fi

    # First boot generates the PKI + server.conf; wait for the agent to
    # answer /sync/health before bringing up OpenVPN so the config exists.
    local health="ok"
    if ! wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 60; then
        health="unreachable"
        warn "Agent did not answer /sync/health — check: journalctl -u $SYSTEMD_SERVICE -n 50"
    fi

    # In Docker the OpenVPN daemon runs inside the container (supervised by
    # the entrypoint) — only manage it on the host for native installs.
    [[ "$DOCKER" -eq 0 ]] && start_openvpn_service
    setup_nat
    setup_logrotate
    open_firewall_ports

    sep; line ""
    step "${B}Installation complete!${NC}"
    line ""
    field "Node name"   "$NODE_NAME"
    field "Mode"        "$([ "$DOCKER" -eq 1 ] && echo Docker || echo Native)"
    field "Service"     "${WH}${scheme}://${host}:${PORT}${NC}"
    field "OpenVPN"     "$(vpn_ports_label)"
    field "API key"     "${GR}${API_KEY}${NC}"
    field "Data"        "$DATA_BASE/$NODE_NAME"
    field "OpenVPN cfg" "$OPENVPN_ROOT/server"
    line ""
    local tls_flag=0; [[ "$TLS_METHOD" != "none" ]] && tls_flag=1
    local bundle="ovnode://${NODE_NAME}@${host}:${PORT}?key=${API_KEY}&tls=${tls_flag}"
    field "Bundle"      "${CY}${bundle}${NC}"
    line ""
    info "Add this node in the panel: Nodes → Add Node → paste the Bundle above"
    info "(or type address ${host}, port ${PORT}, API key above → save)."
    if [[ -n "$EXTRA_PORTS" ]]; then
        info "Clients get all VPN ports (${VPN_PORT},${EXTRA_PORTS}) in their .ovpn"
        info "and fail over automatically if one is blocked."
    fi
    line ""

    emit_result true install \
        mode "$([ "$DOCKER" -eq 1 ] && echo docker || echo native)" \
        node "$NODE_NAME" \
        host "${host:-}" \
        scheme "$scheme" \
        service_port "$PORT" \
        api_key "$API_KEY" \
        bundle "$bundle" \
        vpn_ports "$(vpn_ports_json)" \
        tls "$TLS_METHOD" \
        health "$health" \
        app_dir "$APP_DIR" \
        data_dir "$DATA_BASE/$NODE_NAME" \
        openvpn_root "$OPENVPN_ROOT"
}

# ── Update ─────────────────────────────────────────────────────────────
do_update() {
    [[ -d "$APP_DIR" ]] || die "Not installed ($APP_DIR missing)" "$EX_NOTINSTALLED"
    check_root
    # Recover install parameters from the installed .env when not passed on
    # the CLI, so `update` never silently changes the configuration.
    local env_get; env_get() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"'; }
    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(env_get NODE_NAME)"
    : "${NODE_NAME:=node-1}"
    [[ -n "$PORT" ]] || PORT="$(env_get SERVICE_PORT)"
    : "${PORT:=$DEFAULT_PORT}"
    if [[ -z "$VPN_PORTS" ]]; then
        VPN_PORT="$(env_get OPENVPN_PORT)"; : "${VPN_PORT:=$DEFAULT_VPN}"
        EXTRA_PORTS="$(env_get OVNODE_EXTRA_PORTS)"
    else
        parse_vpn_ports
    fi
    [[ "$TLS_METHOD" != "none" ]] || TLS_METHOD="$(env_get TLS_METHOD)"
    : "${TLS_METHOD:=none}"

    line ""; info "Updating OVNode..."
    detect_os
    # Auto-detect the deployment mode: a compose file means this install was
    # done with --docker, even when `update` is called without the flag.
    if [[ -f "$(compose_file)" ]]; then
        DOCKER=1
        info "Detected Docker deployment (compose file present)"
    fi
    backup_dir "$DATA_BASE" "node"
    backup_dir "$OPENVPN_ROOT/server/pki" "node-pki"

    cd "$APP_DIR"
    if [[ -d .git ]]; then
        git stash --quiet 2>/dev/null || true
        run "Pulling latest changes" git pull --rebase origin "$BRANCH"
        git stash pop --quiet 2>/dev/null || true
    else
        warn "No git checkout — re-downloading source over existing install (.env preserved)"
        run "Downloading source" \
            curl -sSLo /tmp/ovn.tar.gz "https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz"
        tar -xzf /tmp/ovn.tar.gz --strip-components=1 -C "$APP_DIR" >/dev/null 2>&1 || die "Extract failed"
        rm -f /tmp/ovn.tar.gz
    fi

    local scheme="http"
    [[ "$TLS_METHOD" != "none" ]] && scheme="https"

    if [[ "$DOCKER" -eq 1 ]]; then
        run "Rebuilding Docker container" docker compose -f "$(compose_file)" up -d --build
    else
        ensure_uv
        run "Updating Python dependencies" uv_sync
        # Re-write the unit: older installs launched via `uv run`.
        has_systemd && write_systemd_unit
        run "Restarting node agent" systemctl restart "$SYSTEMD_SERVICE"
    fi
    setup_nat
    setup_logrotate

    local health="ok"
    if ! wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 45; then
        health="unreachable"
        warn "Agent did not answer /sync/health after update — check: journalctl -u $SYSTEMD_SERVICE -n 50"
    fi
    step "Update complete"
    line ""

    emit_result true update \
        mode "$([ "$DOCKER" -eq 1 ] && echo docker || echo native)" \
        node "$NODE_NAME" \
        service_port "$PORT" \
        health "$health"
}

# ── Uninstall ──────────────────────────────────────────────────────────
do_uninstall() {
    [[ -d "$APP_DIR" ]] || die "Not installed ($APP_DIR missing)" "$EX_NOTINSTALLED"
    check_root
    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(grep -E '^NODE_NAME=' "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true)"
    : "${NODE_NAME:=node-1}"
    confirm "Remove OVNode and stop all services?" || die "Cancelled."

    # Stopping the NAT unit runs its ExecStop cleanup (rules removed).
    systemctl stop "$SYSTEMD_SERVICE" "$NAT_SERVICE" openvpn-server@server 2>/dev/null || true
    systemctl disable "$SYSTEMD_SERVICE" "$NAT_SERVICE" openvpn-server@server 2>/dev/null || true
    rm -f "/etc/systemd/system/$SYSTEMD_SERVICE" "/etc/systemd/system/$NAT_SERVICE"
    systemctl daemon-reload 2>/dev/null || true

    if command -v docker >/dev/null 2>&1 && [[ -f "$(compose_file)" ]]; then
        ( cd "$APP_DIR" && docker compose -f "$(compose_file)" down ) >/dev/null 2>&1 || true
        docker rm -f "ovnode-$NODE_NAME" >/dev/null 2>&1 || true
    fi

    rm -f "$NAT_SCRIPT" "$NAT_CONF" "$SYSCTL_CONF" "$LOGROTATE_CONF"
    rm -rf "$APP_DIR"
    local purged=false
    if [[ "$PURGE" -eq 1 ]]; then
        backup_dir "$DATA_BASE" "node-pre-purge"
        rm -rf "$DATA_BASE"
        backup_dir "$OPENVPN_ROOT" "openvpn-pre-purge"
        rm -rf "$OPENVPN_ROOT"
        purged=true
        step "Data and OpenVPN configuration removed (backups in /var/backups)"
    else
        step "App removed. Data kept at $DATA_BASE and $OPENVPN_ROOT (use --purge to remove them too)"
    fi
    step "OVNode uninstalled"
    line ""

    emit_result true uninstall node "$NODE_NAME" purged "$purged"
}

# ── Status ─────────────────────────────────────────────────────────────
do_status() {
    local installed=false mode="none" node="" port="" tls="none"
    local agent="unknown" health="unknown" openvpn="unknown" agent_version=""

    if [[ -f "$APP_DIR/.env" ]]; then
        installed=true
        local env_get; env_get() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"'; }
        node="$(env_get NODE_NAME)"; : "${node:=node-1}"
        port="$(env_get SERVICE_PORT)"; : "${port:=$DEFAULT_PORT}"
        tls="$(env_get TLS_METHOD)"; : "${tls:=none}"
        mode="native"
        [[ -f "$DATA_BASE/$node/docker-compose.yml" ]] && mode="docker"

        agent_version="$(grep -Eo '"[0-9]+\.[0-9]+\.[0-9]+"' "$APP_DIR/core/version.py" 2>/dev/null | head -1 | tr -d '"')"

        if [[ "$mode" == "docker" ]]; then
            if command -v docker >/dev/null 2>&1 \
                && docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "ovnode-$node"; then
                agent="running"
            else
                agent="stopped"
            fi
            openvpn="in-container"
        else
            if has_systemd; then
                agent="$(systemctl is-active "$SYSTEMD_SERVICE" 2>/dev/null || true)"
                openvpn="$(systemctl is-active openvpn-server@server 2>/dev/null || true)"
            fi
        fi

        local scheme="http"
        [[ "$tls" != "none" ]] && scheme="https"
        if wait_health "${scheme}://127.0.0.1:${port}/sync/health" 2; then
            health="ok"
        else
            health="unreachable"
        fi
    fi

    field "Installed" "$installed"
    if [[ "$installed" == "true" ]]; then
        field "Mode"      "$mode"
        field "Node"      "$node"
        field "Version"   "${agent_version:-unknown}"
        field "Agent"     "$agent"
        field "OpenVPN"   "$openvpn"
        field "API port"  "$port"
        field "TLS"       "$tls"
        field "Health"    "$health"
    fi

    emit_result true status \
        installed "$installed" \
        mode "$mode" \
        node "$node" \
        agent_version "${agent_version:-}" \
        agent "$agent" \
        openvpn "$openvpn" \
        service_port "${port:-0}" \
        tls "$tls" \
        health "$health"

    [[ "$installed" == "true" ]] || exit "$EX_NOTINSTALLED"
}

# ── Interactive setup (humans on a TTY) ────────────────────────────────
interactive_setup() {
    local api_default
    api_default="$(openssl rand -hex 32)"
    NODE_NAME="$(ask "Node name" "${NODE_NAME:-node-1}")"
    PORT="$(ask "Service port" "${PORT:-$(find_free_port "$DEFAULT_PORT")}")"
    VPN_PORTS="$(ask "OpenVPN port(s), comma sep." "${VPN_PORTS:-$DEFAULT_VPN}")"
    API_KEY="$(ask "API key (blank=generate)" "${API_KEY:-$api_default}")"

    if [[ "$DOCKER" -eq 0 ]]; then
        sep; line "  Deployment:"
        line "  ${WH}1${NC})  Native — systemd services (recommended)"
        line "  ${WH}2${NC})  Docker — agent + OpenVPN in one container"
        local dep; dep="$(ask "Mode" "1")"
        [[ "$dep" == "2" ]] && DOCKER=1
    fi

    sep; line "  TLS (encrypts the panel ↔ node API):"
    line "  ${WH}1${NC})  Let's Encrypt (domain)      needs a domain pointed here + free port 80"
    line "  ${WH}2${NC})  Let's Encrypt (IP)          short-lived cert, no domain needed"
    line "  ${WH}3${NC})  Self-signed                 encrypted; turn TLS *on* in the panel"
    line "  ${WH}4${NC})  Custom cert path            you already have key + cert files"
    line "  ${WH}5${NC})  None (HTTP)                 unsafe on the internet — key travels in cleartext"
    local tls_choice
    tls_choice="$(ask "TLS mode" "3")"
    case "${tls_choice:-3}" in
        1) TLS_METHOD="letsencrypt"; TLS_DOMAIN="$(ask "Domain" "")"; [[ -n "$TLS_DOMAIN" ]] || die "Domain required for Let's Encrypt" ;;
        2) TLS_METHOD="letsencrypt-ip"; TLS_DOMAIN="$(primary_ip)" ;;
        3) TLS_METHOD="selfsigned" ;;
        4) TLS_METHOD="custom"; TLS_KEY="$(ask "Key file" "")"; TLS_CERT="$(ask "Cert file" "")" ;;
        *) TLS_METHOD="none" ;;
    esac
}

# ── Preconditions ──────────────────────────────────────────────────────
check_root() { [[ "$EUID" -eq 0 ]] || die "Must run as root."; }

check_deps() {
    local missing=() cmd
    for cmd in curl tar openssl git; do
        command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
    done
    # Native mode runs the agent + OpenVPN on the host; Docker bundles both
    # in the image, so the host needs neither python nor openvpn.
    if [[ "$DOCKER" -eq 0 ]]; then
        command -v python3 >/dev/null 2>&1 || missing+=("python3")
    fi
    [[ ${#missing[@]} -eq 0 ]] || pkg_install "${missing[@]}"
    if [[ "$DOCKER" -eq 0 ]] && ! command -v openvpn >/dev/null 2>&1; then
        info "Installing OpenVPN + easy-rsa (for client PKI)..."
        pkg_install openvpn easy-rsa
    fi
    step "System dependencies present"
}

# ── Main ───────────────────────────────────────────────────────────────
main() {
    parse_args "$@"
    if fancy; then command clear >/dev/null 2>&1 || true; fi
    line ""
    line "  ${B}OVNode${NC} — OpenVPN Node Agent Installer ${GY}v${VERSION}${NC}"
    sep; line ""

    case "$ACTION" in
        status)    do_status; exit "$EX_OK" ;;
        uninstall) do_uninstall; exit "$EX_OK" ;;
        update)    confirm "Update OVNode now?" || exit "$EX_OK"; do_update; exit "$EX_OK" ;;
    esac

    # Validation must precede the already-installed guard, otherwise a caller
    # invoking `install --port abc --json` gets exit 3 (Already installed)
    # instead of exit 2 + JSON usage error. When CLI flags are present the
    # inputs are checkable right away, even on an already-provisioned host.
    if [[ -n "${API_KEY:-}" || -n "${PORT:-}" || -n "${TLS_METHOD:-}" || -n "${VPN_PORTS:-}" ]]; then
        [[ -n "$PORT" ]]      || PORT="$DEFAULT_PORT"
        [[ -n "$API_KEY" ]]   || true  # validate_input will require it when needed
        [[ -n "$TLS_METHOD" ]]|| TLS_METHOD="none"
        [[ -n "$VPN_PORTS" ]] || VPN_PORTS="$DEFAULT_VPN"
        [[ -n "$NODE_NAME" ]] || NODE_NAME="node-1"
        validate_input
    fi

    # install
    if [[ -d "$APP_DIR" ]]; then
        if [[ "$YES" -eq 1 ]]; then
            die "Already installed ($APP_DIR exists). Run 'update' to refresh or 'uninstall' first." "$EX_ALREADY"
        fi
        warn "OVNode is already installed"
        line ""
        line "  ${GR}1${NC})  Update to latest version"
        line "  ${YL}2${NC})  Uninstall"
        line "  ${GY}3${NC})  Quit"
        line ""
        local choice; choice="$(ask "Select" "3")"
        case "${choice:-3}" in
            1) do_update ;;
            2) do_uninstall ;;
            *) exit "$EX_OK" ;;
        esac
        exit "$EX_OK"
    fi

    detect_os
    if [[ "$YES" -eq 0 ]] && is_tty && [[ -z "$PORT" || -z "$API_KEY" ]]; then
        interactive_setup
    else
        : "${PORT:=$(find_free_port "$DEFAULT_PORT")}"
        : "${VPN_PORTS:=$DEFAULT_VPN}"
        : "${NODE_NAME:=node-1}"
        : "${TLS_METHOD:=none}"
        [[ -n "$API_KEY" ]] || API_KEY="$(openssl rand -hex 32)"
    fi
    validate_input

    field "OS"        "$OS_NAME"
    field "Mode"      "$([ "$DOCKER" -eq 1 ] && echo Docker || echo Native)"
    field "Node"      "$NODE_NAME"
    field "Service"   "$PORT"
    field "OpenVPN"   "$(vpn_ports_label)"
    field "TLS"       "$TLS_METHOD"
    field "Install"   "$APP_DIR"
    field "Data"      "$DATA_BASE/$NODE_NAME"
    if [[ "$TLS_METHOD" == "none" ]]; then
        warn "TLS is DISABLED — the API key is a bearer secret sent in plaintext."
        warn "For internet exposure use --tls letsencrypt/selfsigned; for LAN-only use a private network."
    fi
    sep
    confirm "Proceed with installation?" || die "Cancelled."

    do_install
}

main "$@"
