#!/bin/bash
# Copyright (c) 2026 anonysec
# SPDX-License-Identifier: MIT
#
# ══════════════════════════════════════════════════════════════════════
#  OVNode — OpenVPN Node Agent Installer
#
#  One installer, four ways to run it:
#
#    humans, zero-question:  bash <(curl -Ls URL)
#    humans, wizard        :  bash <(curl -Ls URL) interactive
#    unattended            :  OVN_KEY=$KEY OVN_VPN_PORTS=1194,443 \
#                               bash <(curl -Ls URL) -y
#
#  Three flags, everything else an OVN_* variable (see --help):
#    -y/--yes | --docker | -h/--help
#
#  Commands : install (default) | update | uninstall | interactive |
#             version-script | help
#  Day-to-day ops (status, logs, backup, TLS, completion) live in the
#  manager: ovn.
#  Modes    : host (systemd, default) | --docker (container runs the
#             agent AND OpenVPN, supervised — see docker/entrypoint.sh)
#
#  Unattended (for scripts and AI agents):
#    -y / --yes    never prompts (also implied by no TTY)
#    env overrides OVN_* mirror every setting (CLI wins over env)
#    exit codes    0 ok · 1 error · 2 usage · 3 already installed ·
#                  4 not installed
#
#  What install does: agent (uv venv + systemd unit, or docker compose),
#  OpenVPN scaffolding (PKI + server.conf are generated by the agent on
#  first boot), TLS for the API, IP forwarding + NAT masquerade,
#  multi-port redirects, firewall openings, log rotation, health check.
# ══════════════════════════════════════════════════════════════════════

set -Eeuo pipefail

# ── Constants ──────────────────────────────────────────────────────────
VERSION="1.0.0"
# Forks: point source downloads (and update pulls) at your own repo.
REPO="${OVN_REPO:-anonysec/OVNode}"
# Where the code comes from: versioned GitHub Release tarballs (verified
# checksum, no git needed). Source builds were removed from the production
# installer — developers clone the repo and follow CONTRIBUTING.md.
SRC="release"
# OVN_APP_DIR override exists for hermetic tests: status/uninstall probes
# below must be runnable on machines that already host a node (like CI
# sandboxes and dev boxes) without seeing the real install.
APP_DIR="${OVN_APP_DIR:-/opt/ovnode}"
DATA_BASE="/var/lib/ovnode"
OPENVPN_ROOT="/etc/openvpn"
DEFAULT_PORT=2083
DEFAULT_VPN=1194
SYSTEMD_SERVICE="ovnode.service"
NAT_SERVICE="ovnode-nat.service"
NAT_SCRIPT="/usr/local/sbin/ovnode-nat.sh"
NAT_CONF="/etc/default/ovnode-nat"
SYSCTL_CONF="/etc/sysctl.d/99-ovnode.conf"
LOGROTATE_CONF="/etc/logrotate.d/ovnode"
# Terminal command installed by install_cli() (copy of this installer).
BIN_DIR="${OVN_BIN_DIR:-/usr/local/bin}"
CLI_NAME="ovnode"
CLI_ALIAS="ovn"

# Exit codes (documented in --help; stable for automation)
EX_OK=0 EX_ERROR=1 EX_USAGE=2 EX_ALREADY=3 EX_NOTINSTALLED=4

# ── Settings (env defaults OVN_*, overridden by CLI flags) ─────────────
ACTION="install"
PORT="${OVN_PORT:-}"
API_KEY="${OVN_KEY:-}"
VPN_PORTS="${OVN_VPN_PORTS:-}"
VPN_PROTO="${OVN_PROTO:-}"
NODE_NAME="${OVN_NAME:-}"
TLS_METHOD="${OVN_TLS:-selfsigned}"
TLS_DOMAIN="${OVN_TLS_DOMAIN:-}"
TLS_KEY="${OVN_TLS_KEY:-}"
TLS_CERT="${OVN_TLS_CERT:-}"
DOCKER="${OVN_DOCKER:-0}"
IPV6="${OVN_IPV6:-0}"
NO_NAT="${OVN_NO_NAT:-0}"
YES="${OVN_YES:-0}"
PURGE="${OVN_PURGE:-0}"
QUIET="${OVN_QUIET:-0}"
PIN="${OVN_VERSION:-}"
# True when the caller passed a CLI flag (as opposed to env defaults): used to
# decide whether early validation / the start menu should run.
CLI_FLAGS=0
CMD_GIVEN=0
INTERACTIVE=0
# Set by the start menu: 1 = Express (no further questions).
EXPRESS=0
LOGS_ARG=""
AUTO_BACKUP_ACTION="" BACKUP_TIME="" BACKUP_KEEP=""
# Any OVN_* input present (mirrors CLI flags for early validation / no menu).
ENV_INPUTS=0
for _ovn_var in OVN_PORT OVN_KEY OVN_VPN_PORTS OVN_PROTO OVN_NAME OVN_TLS \
                OVN_TLS_DOMAIN OVN_TLS_KEY OVN_TLS_CERT OVN_DOCKER OVN_IPV6 OVN_NO_NAT; do
    if [[ -n "${!_ovn_var:-}" ]]; then ENV_INPUTS=1; fi
done
unset _ovn_var
# Derived by validate_input:
VPN_PORT="" EXTRA_PORTS=""

# ── Output ─────────────────────────────────────────────────────────────
# Contract: ALL human-readable output goes to stderr, so stdout stays
# clean for callers — nothing the installer prints lands in `$(...)`.
NC=$'\033[0m'; B=$'\033[1m'
WH=$'\033[97m'; GR=$'\033[32m'; RD=$'\033[31m'
YL=$'\033[33m'; CY=$'\033[36m'; GY=$'\033[90m'
[[ -t 2 ]] || { NC=''; B=''; WH=''; GR=''; RD=''; YL=''; CY=''; GY=''; }

# ── Shared helpers (scripts/lib) ───────────────────────────────────────
# line/step/info/warn/field/sep/die, the prompts and the TLS helpers are
# not copied into this file: scripts/lib/*.sh is the only place that
# defines them. A copy beside this script is used when there is one (an
# installed node, a checkout); the curl-piped installer has none and fetches.
#
# The ref to fetch is the one subtlety. "This installer's own VERSION" is right
# in principle — the libs are installer infrastructure, so `-v 1.0.2` must pin
# the app tarball and nothing else — but it is only correct while that tag is at
# least as new as this file, and it is not right now: tag v1.0.0's lib predates
# helpers this file needs. A curl-piped installer comes from a branch and names
# a tag it may not match, so the tag is tried first, main is the fallback, and
# the result is *checked* rather than trusted.
LIB_FILES=(common.sh)   # one entry per file in scripts/lib
LIBS_NEEDED=(die line info warn field sep ask confirm check_root compose_file has_systemd is_docker_node)
LIB_REFS=("v${VERSION}" main)

_libs_are_usable() {  # _libs_are_usable <dir> → 0 when it defines what we call
    # Sourced in a subshell on purpose: a candidate that turns out to be unusable
    # must not leave half its definitions behind for the next candidate to layer on.
    (
        for _l in "${LIB_FILES[@]}"; do
            # shellcheck disable=SC1090
            . "$1/$_l" || exit 1
        done
        for _f in "${LIBS_NEEDED[@]}"; do
            declare -F "$_f" >/dev/null || exit 1
        done
    )
}

# Guarded on purpose: `cat install.sh | bash -s --` (the documented pipe form)
# leaves BASH_SOURCE empty, and `set -u` turns that into "unbound variable"
# before a single line of setup runs. No source path means no local lib to
# look for, so skip straight to the fetch.
LIB_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
    LIB_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || true)/scripts/lib"
    for _lib in "${LIB_FILES[@]}"; do
        [[ -f "$LIB_DIR/$_lib" ]] || LIB_DIR=""
    done
fi
if [[ -z "$LIB_DIR" ]]; then
    LIB_DIR=""
    for _ref in "${LIB_REFS[@]}"; do
        _url="https://raw.githubusercontent.com/${REPO}/${_ref}/scripts/lib"
        _try="$(mktemp -d /tmp/ovn-lib.XXXXXX)"
        _ok=1
        for _lib in "${LIB_FILES[@]}"; do
            curl -fsSL -o "$_try/$_lib" "$_url/$_lib" 2>/dev/null || { _ok=0; break; }
        done
        if [[ "$_ok" -eq 1 ]] && _libs_are_usable "$_try"; then
            LIB_DIR="$_try"
            break
        fi
        rm -rf "$_try"
    done
    if [[ -z "$LIB_DIR" ]]; then
        echo -e "\n  ${RD}Error:${NC} no usable scripts/lib for v${VERSION} or main — the installer cannot run without it. Re-bootstrap with the latest installer: bash <(curl -sSL https://raw.githubusercontent.com/${REPO}/main/install.sh)\n" >&2
        exit "$EX_ERROR"
    fi
fi
# Sourced only once a candidate is in place and known usable, so a partial or
# stale download can never leave a half-defined environment.
for _lib in "${LIB_FILES[@]}"; do
    # shellcheck disable=SC1090
    . "$LIB_DIR/$_lib"
done
[[ "$LIB_DIR" == /tmp/ovn-lib.* ]] && rm -rf "$LIB_DIR"
unset _lib _try _ref _url _ok _l _f

trap 'echo -e "\n  ${RD}Interrupted.${NC}" >&2; exit 130' INT TERM
trap 'warn "Command failed near line $LINENO (running: ${BASH_COMMAND:0:80})"' ERR

# ── OS / package manager ───────────────────────────────────────────────
OS_ID="" OS_NAME="" PKG_INSTALL="" PKG_UPDATE=""

detect_os() {
    [[ -f /etc/os-release ]] || die "Unsupported OS — no /etc/os-release found."
    # /etc/os-release defines its own VERSION — keep the app version.
    local _app_version="$VERSION"
    # shellcheck disable=SC1091
    . /etc/os-release
    VERSION="$_app_version"
    OS_ID="${ID:-}"; OS_NAME="${PRETTY_NAME:-$OS_ID}"
    case "$OS_ID" in
        debian|ubuntu)      PKG_UPDATE="apt-get update -qq";  PKG_INSTALL="apt-get install -y -qq" ;;
        rhel|centos|rocky|almalinux|fedora)
            if command -v dnf >/dev/null 2>&1; then
                PKG_UPDATE="dnf -q makecache"; PKG_INSTALL="dnf install -y -q"
            else
                PKG_UPDATE="yum -q makecache"; PKG_INSTALL="yum install -y -q"
            fi ;;
        arch)               PKG_UPDATE="pacman -Sy --noconfirm"; PKG_INSTALL="pacman -S --noconfirm" ;;
        alpine)             PKG_UPDATE="apk update -q";          PKG_INSTALL="apk add -q" ;;
        *) die "Unsupported distribution: ${OS_ID:-unknown}" ;;
    esac
}

pkg_install() {
    info "Installing: $*"
    $PKG_UPDATE >/dev/null 2>&1 || true
    $PKG_INSTALL "$@" >/dev/null 2>&1 || die "Failed to install: $*"
}

# ── Help / args ────────────────────────────────────────────────────────
# One line per flag that left the three-flag surface. It goes to stderr and
# it is not routed through line()/warn(): those are silenced by --quiet and
# by a non-TTY, and a deprecation the operator never sees is not a
# deprecation. The flags still work — removal is the next release.
deprecated() {  # deprecated <flag> <what to do instead>
    printf '  %s⚠%s %s is deprecated; %s\n' "$YL" "$NC" "$1" "$2" >&2
}

# The installer's own identity, for support: "which installer did you
# actually run?". A curl-piped run is always the newest file, but the raw
# CDN caches for minutes, so a stale copy is normal rather than a mystery.
# printf, not field(): field() is silenced by --quiet, and this command
# exists precisely to be read back by somebody else. The commit is printed
# only when something stamped it — this installer has no code path that
# knows its own SHA, and inventing one would be worse than saying so.
print_script_version() {
    printf '  %-18s %s\n' "Installer" "install.sh v${VERSION}" >&2
    printf '  %-18s %s\n' "Commit" \
        "${OVN_SCRIPT_COMMIT:-not recorded (this installer carries no commit stamp)}" >&2
    exit "$EX_OK"
}

show_help() {
    cat << EOF >&2
  OVNode installer — host (systemd) or Docker, interactive or unattended.

  Usage:
    bash <(curl -Ls URL) [command] [flags]

  No command? Zero-question install with safe generated values.
  The start menu offers Install (host service) or Install with Docker.
  The \`interactive\` command opens the numbered wizard instead.
  Installs use safe defaults (ovnode, UDP, self-signed TLS,
  generated API key). Plain HTTP is not offered.

  Commands: (default: install)
    update                Fetch the verified release and restart (state
                          safety snapshot + code snapshot first,
                          auto-rollback on failure)
    recover-update        Recover an interrupted update transaction
    repair-unit           Regenerate systemd unit / NAT / logrotate
    uninstall             Remove OVNode (data kept unless OVN_PURGE=1)
    interactive, -i       Numbered install wizard (Enter = default)
    version-script        Print this installer's own version and commit
    help                  This help

  Everything else (status, logs, backup, restore, TLS, completion) lives
  in the manager: ovn  (installed as ovnode/ovn).

  Options (every option has an OVN_* env equivalent; CLI wins):
    -y, --yes             Never prompt, accept defaults       [OVN_YES=1]
    --docker              Deploy in Docker (container runs agent + OpenVPN,
                          host networking)                    [OVN_DOCKER=1]

  -h, --help              This help  (no env equivalent)

  Deprecated (still works) — each flag is removed next release. Set the
  OVN_* variable instead:
    -p, --key KEY         API key, min 16 chars (generated if omitted)
                                                              [OVN_KEY]
    --name NAME           Node name                  [OVN_NAME, ovnode]
    --port PORT           Sync API port                     [OVN_PORT, 2083]
    --vpn-ports LIST      OpenVPN ports, comma separated [OVN_VPN_PORTS, 1194]
                          First = listener; the rest are redirected to it and
                          included in every .ovpn (client failover).
    --proto PROTO         VPN transport: udp (default, faster) or tcp
                          (fallback where UDP is blocked)          [OVN_PROTO]
    --tls 1|2|3|4         1 selfsigned (default), 2 letsencrypt,
                          3 letsencrypt-ip, 4 custom               [OVN_TLS]
                          Plain HTTP ("none") is rejected.
    --tls-domain DOM      Domain/IP for Let's Encrypt      [OVN_TLS_DOMAIN]
    --tls-key  FILE       Private key (--tls 4)             [OVN_TLS_KEY]
    --tls-cert FILE       Certificate (--tls 4)            [OVN_TLS_CERT]
    --ipv6                Enable IPv6 on the VPN            [OVN_IPV6=1]
    --no-nat              Skip forwarding/NAT/redirects     [OVN_NO_NAT=1]
    --purge               With uninstall: remove data too   [OVN_PURGE=1]
    --quiet | -q          Suppress progress logs (errors still shown)
                                                           [OVN_QUIET=1]
    -v, --version vX.Y.Z  Install/update this release instead of v${VERSION}
                                                          [OVN_VERSION]
    --from-release        Download the versioned release file [default]
                          [no replacement — verified releases are the only
                          source now, so just drop the flag]

  Exit codes:
    0 success · 1 error · 2 usage error · 3 already installed ·
    4 not installed

  Unattended example (never prompts; branch on the exit code):
    OVN_KEY="\$API_KEY" bash install.sh -y
EOF
    exit "$EX_OK"
}

parse_args() {
    local need2='[[ $# -ge 2 ]] || die "$1 needs a value" "$EX_USAGE"'
    while [[ $# -gt 0 ]]; do
        case "$1" in
            update)       ACTION="update"; CMD_GIVEN=1; shift ;;
            uninstall) ACTION="uninstall"; CMD_GIVEN=1; shift ;;
            recover-update) ACTION="recover-update"; CMD_GIVEN=1; shift ;;
            repair-unit) ACTION="repair-unit"; CMD_GIVEN=1; shift ;;
            version-script|script-version) print_script_version ;;
            help|--help|-h) show_help ;;
            --port)       eval "$need2"; deprecated "--port" "set OVN_PORT instead"; PORT="$2"; CLI_FLAGS=1; shift 2 ;;
            -p|--key)       eval "$need2"; deprecated "$1" "set OVN_KEY instead"; API_KEY="$2"; CLI_FLAGS=1; shift 2 ;;
            -v|--version)   eval "$need2"; deprecated "$1" "set OVN_VERSION instead"; PIN="$2"; CLI_FLAGS=1; shift 2 ;;
            -i)             ACTION="interactive"; CMD_GIVEN=1; shift ;;
            --vpn-ports|--vpn-port) eval "$need2"; deprecated "$1" "set OVN_VPN_PORTS instead"; VPN_PORTS="$2"; CLI_FLAGS=1; shift 2 ;;
            --proto) eval "$need2"; deprecated "--proto" "set OVN_PROTO instead"; VPN_PROTO="$2"; CLI_FLAGS=1; shift 2 ;;
            --name)       eval "$need2"; deprecated "--name" "set OVN_NAME instead"; NODE_NAME="$2"; CLI_FLAGS=1; shift 2 ;;
            --tls)        eval "$need2"; deprecated "--tls" "set OVN_TLS instead"; CLI_FLAGS=1
                          case "$2" in
                              1|selfsigned) TLS_METHOD="selfsigned" ;;
                              2|letsencrypt) TLS_METHOD="letsencrypt" ;;
                              3|letsencrypt-ip) TLS_METHOD="letsencrypt-ip" ;;
                              4|custom) TLS_METHOD="custom" ;;
                              *) die "Invalid --tls '$2' (use 1, 2, 3 or 4)" "$EX_USAGE" ;;
                          esac
                          shift 2 ;;
            --tls-domain) eval "$need2"; deprecated "--tls-domain" "set OVN_TLS_DOMAIN instead"; TLS_DOMAIN="$2"; CLI_FLAGS=1; shift 2 ;;
            --tls-key)    eval "$need2"; deprecated "--tls-key" "set OVN_TLS_KEY instead"; TLS_KEY="$2"; CLI_FLAGS=1; shift 2 ;;
            --tls-cert)   eval "$need2"; deprecated "--tls-cert" "set OVN_TLS_CERT instead"; TLS_CERT="$2"; CLI_FLAGS=1; shift 2 ;;
            --docker)     DOCKER=1; CLI_FLAGS=1; shift ;;
            --from-release) deprecated "--from-release" "verified releases are the only source now, so just drop it"; SRC="release"; CLI_FLAGS=1; shift ;;
            --ipv6)       deprecated "--ipv6" "set OVN_IPV6=1 instead"; IPV6=1; CLI_FLAGS=1; shift ;;
            --no-nat)     deprecated "--no-nat" "set OVN_NO_NAT=1 instead"; NO_NAT=1; CLI_FLAGS=1; shift ;;
            --yes|-y)     YES=1; CLI_FLAGS=1; shift ;;
            --purge)      deprecated "--purge" "set OVN_PURGE=1 instead"; PURGE=1; CLI_FLAGS=1; shift ;;
            --quiet|-q)   deprecated "$1" "set OVN_QUIET=1 instead"; QUIET=1; shift ;;
            status|start|stop|restart|restart-vpn|logs|backup|auto-backup|tls)
                          die "'$1' moved to the manager — use: ovn $1" "$EX_USAGE" ;;
            menu)         die "The menu lives in the manager — run: ovn" "$EX_USAGE" ;;
            install)      die "'install' is the default — just drop the word" "$EX_USAGE" ;;
            interactive)  ACTION="interactive"; CMD_GIVEN=1; shift ;;
            *)            die "Unknown option: $1 (--help for usage)" "$EX_USAGE" ;;
        esac
    done
    # No TTY = nobody to answer prompts: behave as --yes.
    is_tty || YES=1
}

# ── Validation ─────────────────────────────────────────────────────────

# A release version: MAJOR.MINOR.PATCH, optionally with a pre-release or build
# suffix (1.2.3-rc1, 1.2.3+build5), and an optional leading v. The suffix is
# what lets a pre-release be installed by name, and the tag it resolves to is
# "v" + this (see release_url), so both spellings of the same release work.
valid_release_version() {
    [[ "$1" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]
}

# Splits VPN_PORTS ("1194,443,8443") into VPN_PORT (primary listener) and
# EXTRA_PORTS (comma separated, redirected to the primary).
parse_vpn_ports() {
    local raw="${VPN_PORTS:-$DEFAULT_VPN}" seen=" " port
    VPN_PORT="" EXTRA_PORTS=""
    IFS=',' read -ra _ports <<< "${raw// /}"
    for port in "${_ports[@]}"; do
        [[ -z "$port" ]] && continue
        is_port "$port" || die "Invalid OpenVPN port: '$port'" "$EX_USAGE"
        [[ "$seen" == *" $port "* ]] && continue
        seen+="$port "
        if [[ -z "$VPN_PORT" ]]; then
            VPN_PORT="$port"
        else
            EXTRA_PORTS="${EXTRA_PORTS:+$EXTRA_PORTS,}$port"
        fi
    done
    [[ -n "$VPN_PORT" ]] || die "At least one OpenVPN port is required" "$EX_USAGE"
}

# One place mints the key, so the note on the Ready card cannot disagree with
# what actually happened. An operator-supplied key must not be reported as
# generated.
generate_api_key() {
    API_KEY="$(openssl rand -hex 32)"
    KEY_GENERATED=1
}

validate_input() {
    is_port "$PORT" || die "Invalid service port: '$PORT'" "$EX_USAGE"
    parse_vpn_ports
    [[ "$VPN_PORT" == "$PORT" ]] && die "OpenVPN port and service port must differ" "$EX_USAGE"
    # Normalize transport early so every consumer sees tcp|udp only.
    # UDP is the default: faster, and the panel can switch a node to TCP later.
    VPN_PROTO="$(echo "${VPN_PROTO:-udp}" | tr '[:upper:]' '[:lower:]')"
    case "$VPN_PROTO" in
        udp|tcp) ;;
        *) die "Invalid transport '$VPN_PROTO' (use udp or tcp)" "$EX_USAGE" ;;
    esac
    [[ -n "$NODE_NAME" ]] || NODE_NAME="ovnode"
    [[ "$NODE_NAME" =~ ^[A-Za-z0-9_-]{1,64}$ ]] || die "Invalid node name" "$EX_USAGE"
    [[ -n "$API_KEY" ]] || generate_api_key
    [[ ${#API_KEY} -ge 16 ]] || die "API key must be at least 16 characters (openssl rand -hex 32)" "$EX_USAGE"
    case "$TLS_METHOD" in
        letsencrypt|letsencrypt-ip|selfsigned|custom) ;;
        none) die "Plain HTTP is not allowed — pick selfsigned (default), letsencrypt, letsencrypt-ip or custom" "$EX_USAGE" ;;
        *) die "Invalid TLS method: '$TLS_METHOD'" "$EX_USAGE" ;;
    esac
    if [[ "$TLS_METHOD" == "letsencrypt" || "$TLS_METHOD" == "letsencrypt-ip" ]]; then
        [[ -n "$TLS_DOMAIN" ]] || die "--tls-domain is required for Let's Encrypt" "$EX_USAGE"
    fi
    if [[ "$TLS_METHOD" == "custom" ]]; then
        [[ -f "$TLS_KEY" && -f "$TLS_CERT" ]] || die "Custom TLS key/cert files not found" "$EX_USAGE"
    fi
}

port_in_use() {
    command -v ss >/dev/null 2>&1 || return 1
    ss -ltn 2>/dev/null | awk -v p=":${1}$" '$4 ~ p {exit 0} END {exit 1}'
}

find_free_port() {
    local port="${1:-$DEFAULT_PORT}"
    while port_in_use "$port"; do ((port++)); done
    echo "$port"
}

vpn_ports_label() {
    if [[ -n "$EXTRA_PORTS" ]]; then
        echo "${VPN_PORT} (+ redirects: ${EXTRA_PORTS})"
    else
        echo "$VPN_PORT"
    fi
}

# ── Toolchain ──────────────────────────────────────────────────────────
UV_BIN=""
ensure_uv() {
    if command -v uv >/dev/null 2>&1; then
        UV_BIN="$(command -v uv)"; step "uv found: $UV_BIN"; return
    fi
    info "Installing uv (Python package manager)..."
    curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null 2>&1 || \
        python3 -m pip install --quiet uv >/dev/null 2>&1 || \
        die "Could not install uv."
    UV_BIN="$(command -v uv 2>/dev/null || true)"
    [[ -n "$UV_BIN" ]] || UV_BIN="$HOME/.local/bin/uv"
    [[ -x "$UV_BIN" ]] || die "uv not found after install"
    step "uv installed: $UV_BIN"
}

# Reproducible dependency install: the lockfile pins exact versions.
# Fall back to a fresh resolve only when the lock cannot be honored.
uv_sync() {
    "$UV_BIN" sync --frozen --no-dev --quiet 2>/dev/null \
        || "$UV_BIN" sync --no-dev --quiet
}

# ── Forwarding / NAT / multi-port redirects ────────────────────────────
# IP forwarding is a host sysctl in BOTH modes (a container usually cannot
# write /proc/sys). The iptables rules live in one idempotent script owned
# by a oneshot systemd unit — native mode only; in Docker the entrypoint
# applies the equivalent rules itself via CAP_NET_ADMIN.
write_sysctl() {
    cat > "$SYSCTL_CONF" << 'SYSCTL'
# OVNode: allow OpenVPN clients to route through this host
net.ipv4.ip_forward = 1
SYSCTL
    if [[ "$IPV6" -eq 1 ]]; then
        echo "net.ipv6.conf.all.forwarding = 1" >> "$SYSCTL_CONF"
    fi
    sysctl -p "$SYSCTL_CONF" >/dev/null 2>&1 || true
    step "IP forwarding enabled ($SYSCTL_CONF)"
}

write_nat_files() {
    cat > "$NAT_CONF" << CONF
# OVNode NAT configuration (managed by install.sh)
VPN_PRIMARY_PORT=${VPN_PORT}
VPN_EXTRA_PORTS=${EXTRA_PORTS}
CONF

    cat > "$NAT_SCRIPT" << 'NAT'
#!/bin/bash
# OVNode NAT: masquerade VPN client traffic through the default uplink and
# redirect the extra VPN ports to the OpenVPN listener. Idempotent.
# Usage: ovnode-nat.sh [apply|cleanup]
set -u
CONF="/etc/default/ovnode-nat"
VPN_PRIMARY_PORT="" VPN_EXTRA_PORTS="" VPN_SUBNET="10.8.0.0/24" VPN_TUN_DEV="tun0"
# shellcheck disable=SC1090
[[ -f "$CONF" ]] && . "$CONF"

rule() {  # rule <add|del> <table> <chain> <args...>
    local op="$1" table="$2" chain="$3"; shift 3
    if [[ "$op" == "add" ]]; then
        iptables -t "$table" -C "$chain" "$@" 2>/dev/null || iptables -t "$table" -A "$chain" "$@"
    else
        iptables -t "$table" -D "$chain" "$@" 2>/dev/null || true
    fi
}

each_redirect() {  # each_redirect <add|del>
    local op="$1" port proto
    [[ -n "$VPN_PRIMARY_PORT" && -n "$VPN_EXTRA_PORTS" ]] || return 0
    for port in ${VPN_EXTRA_PORTS//,/ }; do
        for proto in tcp udp; do
            rule "$op" nat PREROUTING -p "$proto" --dport "$port" \
                -j REDIRECT --to-ports "$VPN_PRIMARY_PORT"
        done
    done
}

IFACE="$(ip route show default 2>/dev/null | awk '{print $5; exit}')"

# Docker and other hardening set FORWARD policy DROP, which kills masqueraded
# client traffic after POSTROUTING. Accept the VPN subnet through the
# DOCKER-USER admin hook (evaluated before Docker's own jumps; recreated
# empty by Docker, so re-added here on every apply).
forward_rules() {  # forward_rules <add|del>
    local op="$1"
    iptables -L DOCKER-USER -n >/dev/null 2>&1 || return 0
    rule "$op" filter DOCKER-USER -s "$VPN_SUBNET" -i "$VPN_TUN_DEV" -o "$IFACE" -j ACCEPT
    rule "$op" filter DOCKER-USER -i "$IFACE" -o "$VPN_TUN_DEV" \
        -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
}

case "${1:-apply}" in
    apply)
        if [[ -z "$IFACE" ]]; then echo "ovnode-nat: no default interface found" >&2; exit 1; fi
        rule add nat POSTROUTING -o "$IFACE" -j MASQUERADE
        each_redirect add
        forward_rules add
        ;;
    cleanup)
        [[ -n "$IFACE" ]] && rule del nat POSTROUTING -o "$IFACE" -j MASQUERADE
        each_redirect del
        [[ -n "$IFACE" ]] && forward_rules del
        ;;
    *) echo "usage: $0 [apply|cleanup]" >&2; exit 2 ;;
esac
NAT
    chmod +x "$NAT_SCRIPT"

    cat > "/etc/systemd/system/$NAT_SERVICE" << UNIT
[Unit]
Description=OVNode NAT (masquerade + VPN port redirects)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$NAT_SCRIPT apply
ExecStop=$NAT_SCRIPT cleanup

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload >/dev/null 2>&1
    systemctl enable "$NAT_SERVICE" >/dev/null 2>&1
    if systemctl restart "$NAT_SERVICE" >/dev/null 2>&1; then
        if [[ -n "$EXTRA_PORTS" ]]; then
            step "NAT enabled, ports ${EXTRA_PORTS} → ${VPN_PORT}"
        else
            step "NAT enabled"
        fi
    else
        warn "Could not start NAT service — VPN clients may not route traffic"
    fi
}

setup_nat() {
    if [[ "$NO_NAT" -eq 1 ]]; then info "Skipping NAT setup (--no-nat)"; return 0; fi
    write_sysctl
    if [[ "$DOCKER" -eq 1 ]]; then
        info "Docker mode: NAT/redirect rules are applied inside the container (CAP_NET_ADMIN)"
        return 0
    fi
    if ! command -v iptables >/dev/null 2>&1; then
        pkg_install iptables iproute2
    fi
    write_nat_files
}

# ── Log rotation ───────────────────────────────────────────────────────
# server.conf uses `log-append openvpn.log`, which grows without bound and
# will eventually fill a small VPS disk (killing OpenVPN with it). The
# agent log rotates itself; the OpenVPN log needs logrotate. Native
# installs SIGHUP the daemon (clean reopen, no teardown); Docker keeps
# copytruncate because the daemon's PID namespace is unreachable from a
# host logrotate postrotate.
setup_logrotate() {
    if ! command -v logrotate >/dev/null 2>&1; then
        if [[ -n "$PKG_INSTALL" ]]; then
            pkg_install logrotate
        else
            warn "logrotate not found — install it so openvpn.log gets rotated"
            return 0
        fi
    fi
    if [[ "${DOCKER:-0}" -eq 1 ]]; then
        cat > "$LOGROTATE_CONF" << ROTATE
${OPENVPN_ROOT}/server/openvpn.log {
    size 10M
    rotate 3
    compress
    missingok
    notifempty
    copytruncate
}
ROTATE
    else
        cat > "$LOGROTATE_CONF" << ROTATE
${OPENVPN_ROOT}/server/openvpn.log {
    size 10M
    rotate 3
    compress
    missingok
    notifempty
    postrotate
        systemctl kill -s HUP openvpn-server@server >/dev/null 2>&1 || true
    endscript
}
ROTATE
    fi
    step "Log rotation configured ($LOGROTATE_CONF)"
}

# ── OpenVPN scaffolding ────────────────────────────────────────────────
ensure_openvpn_dirs() {
    mkdir -p "$OPENVPN_ROOT/server" "$OPENVPN_ROOT/ccd" \
             "$OPENVPN_ROOT/ovnode/users" "$OPENVPN_ROOT/ovnode/sessions" \
             "$OPENVPN_ROOT/ovnode/scripts" "$OPENVPN_ROOT/ovnode/usage"
    # Some distros (Arch) lack the "nogroup" group that the generated
    # server.conf references — create it so OpenVPN can start.
    getent group nogroup >/dev/null 2>&1 || groupadd -r nogroup 2>/dev/null || true
    # The tun device is required; try to load the kernel module if missing.
    if [[ ! -e /dev/net/tun ]]; then
        mkdir -p /dev/net
        modprobe tun 2>/dev/null || true
        mknod /dev/net/tun c 10 200 2>/dev/null || true
        chmod 600 /dev/net/tun 2>/dev/null || true
    fi
    if [[ -e /dev/net/tun ]]; then
        step "OpenVPN directories ready ($OPENVPN_ROOT), /dev/net/tun present"
    else
        warn "/dev/net/tun is missing — OpenVPN cannot start (Docker: mount it, bare-metal: modprobe tun)"
    fi
}

start_openvpn_service() {
    # The agent generates server.conf + PKI on first boot; enable/start the
    # systemd instance that reads it.
    if has_systemd; then
        systemctl enable openvpn-server@server >/dev/null 2>&1 || true
        systemctl restart openvpn-server@server >/dev/null 2>&1 && \
            step "OpenVPN server service started" || \
            warn "Could not start openvpn-server@server — check: journalctl -u openvpn-server@server -n 50"
    elif command -v rc-service >/dev/null 2>&1; then
        rc-update add openvpn default >/dev/null 2>&1 || true
        rc-service openvpn start >/dev/null 2>&1 && step "OpenVPN started (OpenRC)" || warn "Start OpenVPN manually"
    else
        warn "No init system detected — start OpenVPN manually: openvpn --config $OPENVPN_ROOT/server/server.conf"
    fi
}

# Mandatory post-flight for Docker mode (twice bitten): the container's
# OpenVPN must own 1194/7505. A native daemon holding those ports on the
# shared host network namespace crash-loops the container's OpenVPN
# (mgmt bind EADDRINUSE), while the agent health check stays green.
check_container_openvpn() {
    local cid=""
    cid="$(docker compose -f "$(compose_file)" ps -q 2>/dev/null | head -n 1)"
    if [[ -n "$cid" ]] && docker exec "$cid" pgrep -x openvpn >/dev/null 2>&1; then
        step "OpenVPN running in container"
    else
        warn "OpenVPN not detected in container — check: docker logs ${NODE_NAME}; host stray check: ss -tlnp | grep -E '1194|7505'"
    fi
}

stop_native_openvpn() {
    # Docker mode only: OpenVPN runs inside the container on the shared host
    # network namespace, so a native daemon holding 1194/7505 crash-loops
    # the container's OpenVPN (seen twice: a stray, then a restarted unit).
    # Native installs are untouched — start_openvpn_service owns that path.
    if has_systemd; then
        if systemctl is-active --quiet openvpn-server@server 2>/dev/null; then
            run "Stopping conflicting native openvpn-server@server (Docker mode)" \
                systemctl stop openvpn-server@server
        fi
        systemctl disable openvpn-server@server >/dev/null 2>&1 || true
    elif command -v rc-service >/dev/null 2>&1; then
        rc-service openvpn stop >/dev/null 2>&1 || true
    fi
}

# ── Firewall ───────────────────────────────────────────────────────────
# Every VPN port is opened for BOTH protocols: the panel can switch the
# node between udp and tcp at runtime, and the extra-port redirects always
# cover both.
open_firewall_ports() {
    local vpn_all="$VPN_PORT ${EXTRA_PORTS//,/ }" p
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw allow "$PORT/tcp" >/dev/null 2>&1
        for p in $vpn_all; do
            ufw allow "$p/udp" >/dev/null 2>&1
            ufw allow "$p/tcp" >/dev/null 2>&1
        done
        step "UFW: allowed $PORT/tcp + VPN port(s) ${vpn_all// /, }"
    elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
        firewall-cmd --permanent --add-port="$PORT/tcp" >/dev/null 2>&1
        for p in $vpn_all; do
            firewall-cmd --permanent --add-port="$p/udp" >/dev/null 2>&1
            firewall-cmd --permanent --add-port="$p/tcp" >/dev/null 2>&1
        done
        firewall-cmd --reload >/dev/null 2>&1
        step "firewalld: allowed $PORT/tcp + VPN port(s) ${vpn_all// /, }"
    fi
}

# Mirror of open_firewall_ports for uninstall: remove exactly what an
# install would have opened, using the INSTALLED .env values (flags may
# differ from install time). Best-effort — never fail the uninstall.
close_firewall_ports() {
    local env_get; env_get() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true; }
    local svc vpn extras p vpn_all
    svc="$(env_get SERVICE_PORT)"; : "${svc:=$DEFAULT_PORT}"
    vpn="$(env_get OPENVPN_PORT)"; : "${vpn:=$DEFAULT_VPN}"
    extras="$(env_get OVNODE_EXTRA_PORTS)"
    vpn_all="$vpn ${extras//,/ }"
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw delete allow "$svc/tcp" >/dev/null 2>&1 || true
        for p in $vpn_all; do
            ufw delete allow "$p/udp" >/dev/null 2>&1 || true
            ufw delete allow "$p/tcp" >/dev/null 2>&1 || true
        done
        step "UFW: removed $svc/tcp + VPN port(s) ${vpn_all// /, }"
    elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
        firewall-cmd --permanent --remove-port="$svc/tcp" >/dev/null 2>&1 || true
        for p in $vpn_all; do
            firewall-cmd --permanent --remove-port="$p/udp" >/dev/null 2>&1 || true
            firewall-cmd --permanent --remove-port="$p/tcp" >/dev/null 2>&1 || true
        done
        firewall-cmd --reload >/dev/null 2>&1 || true
        step "firewalld: removed $svc/tcp + VPN port(s) ${vpn_all// /, }"
    fi
}

# ── Systemd unit ───────────────────────────────────────────────────────
write_systemd_unit() {
    # ExecStart runs the venv interpreter directly: no uv resolution at
    # boot, one fewer process, faster restarts, lower RAM.
    cat > "/etc/systemd/system/$SYSTEMD_SERVICE" << UNIT
[Unit]
Description=OVNode OpenVPN Node Agent (${NODE_NAME})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=${APP_DIR}
Environment="PATH=${APP_DIR}/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
EnvironmentFile=${APP_DIR}/.env
ExecStart=${APP_DIR}/.venv/bin/python ${APP_DIR}/main.py
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload >/dev/null 2>&1
    systemctl enable "$SYSTEMD_SERVICE" >/dev/null 2>&1
    step "systemd unit written: /etc/systemd/system/$SYSTEMD_SERVICE"
}

# ── Source / environment ───────────────────────────────────────────────
release_base() { printf 'ovnode-%s' "$VERSION"; }

release_url() {
    printf 'https://github.com/%s/releases/download/v%s/%s.tar.gz' \
        "$REPO" "$VERSION" "$(release_base)"
}

release_checksum_url() {
    printf 'https://github.com/%s/releases/download/v%s/%s.sha256' \
        "$REPO" "$VERSION" "$(release_base)"
}

IMAGE_REPO="ghcr.io/${REPO,,}"

# ── Transactional update state ────────────────────────────────────────
# Journal + lock live beside node state (host paths in both modes: Docker
# bind-mounts DATA_BASE). The maintenance marker lives inside the node's
# own data dir so the agent (settings.data_dir, also /app/data in Docker)
# sees the same file the installer writes. Staging/previous live beside
# the app.
UPDATE_STATE="${DATA_BASE}/update-state.json"
update_marker() { printf '%s' "${DATA_BASE}/${NODE_NAME:-ovnode}/update-maintenance"; }
UPDATE_STAGE="$(dirname "$APP_DIR")/.ovnode.staging"
UPDATE_PREVIOUS="$(dirname "$APP_DIR")/.ovnode.previous"
OP_LOCK="${DATA_BASE}/.operation.lock"
OP_LOCK_HELD=0

operation_begin() {
    local name="$1" owner=""
    mkdir -p "$DATA_BASE"
    if ! mkdir "$OP_LOCK" 2>/dev/null; then
        owner="$(cat "$OP_LOCK/pid" 2>/dev/null || true)"
        if [[ "$owner" =~ ^[0-9]+$ ]] && ! kill -0 "$owner" 2>/dev/null; then
            warn "Removing stale operation lock from process $owner"
            rm -rf "$OP_LOCK"
            mkdir "$OP_LOCK" || die "Another maintenance operation is running" "$EX_ERROR"
        else
            die "Another maintenance operation is running${owner:+ (process $owner)}. Try again later." "$EX_ERROR"
        fi
    fi
    printf '%s\n' "$$" > "$OP_LOCK/pid"
    printf '%s\n' "$name" > "$OP_LOCK/action"
    chmod 700 "$OP_LOCK"
    OP_LOCK_HELD=1
}

operation_end() {
    [[ "$OP_LOCK_HELD" -eq 1 ]] || return 0
    rm -rf "$OP_LOCK"
    OP_LOCK_HELD=0
}

# Persist one transaction phase atomically (0600): power loss or kill -9
# can never leave a half-written journal.
update_state() {
    local phase="$1" from="${2:-unknown}" target="${3:-$VERSION}" backup="${4:-}" identity="${5:-}"
    mkdir -p "$DATA_BASE"
    python3 - "$UPDATE_STATE" "$phase" "$from" "$target" "$backup" "$identity" <<'PY'
import json, os, sys, tempfile, time
path, phase, old, target, backup, identity = sys.argv[1:]
data = {"phase": phase, "from_version": old, "to_version": target,
        "safety_backup": backup or None, "identity_sha": identity or None,
        "updated_at": int(time.time()), "pid": os.getppid()}
fd, tmp = tempfile.mkstemp(prefix=".update-state-", dir=os.path.dirname(path))
try:
    with os.fdopen(fd, "w") as f:
        json.dump(data, f, indent=2); f.write("\n"); f.flush(); os.fsync(f.fileno())
    os.chmod(tmp, 0o600); os.replace(tmp, path)
finally:
    try: os.unlink(tmp)
    except FileNotFoundError: pass
PY
}

# sha256(node-name + API key): proves identity survived activation without
# ever persisting a secret in the journal.
identity_sha() {
    python3 - "$1" "$2" <<'PY'
import hashlib, sys
print(hashlib.sha256(("|".join(sys.argv[1:])).encode()).hexdigest())
PY
}

# A broken download (redirect stub, proxy block page) must fail here with
# a clear message — never as a checksum mismatch further down.
is_release_archive() { tar -tzf "$1" >/dev/null 2>&1; }

# Download the versioned release file into $1 (an existing directory).
# The .sha256 sidecar is mandatory: unverified code is never installed.
fetch_release() {
    local dest="$1" work base
    base="$(release_base)"
    work="$(mktemp -d /tmp/ovn.XXXXXX)"
    run "Downloading release v${VERSION}" \
        curl -fsSL -o "$work/$base.tar.gz" "$(release_url)" \
        || { rm -rf "$work"; die "No release file for v${VERSION}" "$EX_ERROR"; }
    is_release_archive "$work/$base.tar.gz" \
        || { rm -rf "$work"; die "Download for v${VERSION} is not a release archive (stale installer or blocked download?). Re-bootstrap with the latest installer:  bash <(curl -sSL https://raw.githubusercontent.com/${REPO}/main/install.sh)" "$EX_ERROR"; }
    curl -fsSL -o "$work/$base.sha256" "$(release_checksum_url)" 2>/dev/null \
        || { rm -rf "$work"; die "Release checksum file is missing for v${VERSION}" "$EX_ERROR"; }
    ( cd "$work" && sha256sum -c "$base.sha256" >/dev/null ) \
        || { rm -rf "$work"; die "Release checksum mismatch for v${VERSION}" "$EX_ERROR"; }
    step "Checksum ok"
    mkdir -p "$dest"
    # --no-same-owner: an archive from an older release still carries whatever
    # uid built it, and extracting as root would restore that. The install runs
    # as root, so honouring the archive's numeric ids is exactly backwards.
    tar --no-same-owner -xzf "$work/$base.tar.gz" -C "$dest" >/dev/null 2>&1 || { rm -rf "$work"; die "Extract failed" "$EX_ERROR"; }
    # Root-owned explicitly, so the tree does not depend on how it was built.
    chown -R root:root "$dest"
    rm -rf "$work"
    step "Release extracted"
}

fetch_source() {
    # Release-only installer: source builds were removed. Developers clone
    # the repo and follow CONTRIBUTING.md.
    die "Source installs were removed — the installer consumes verified releases only" "$EX_USAGE"
}

# Verified safety snapshot of every persistent node state needed for
# rollback: identity (.env), node data dir, OpenVPN state, API TLS files.
# Single manifest-linked tarball; restore consumes it after verification.
state_safety_bundle() {
    local from_version="$1" backup_root="/var/backups"
    local node_data="${DATA_BASE}/${NODE_NAME}"
    mkdir -p "$backup_root" "$node_data"
    python3 - "$APP_DIR" "$node_data" "$OPENVPN_ROOT" "$backup_root" "$NODE_NAME" "$from_version" <<'PY' || return 1
import hashlib, json, os, sys, tarfile, tempfile
from datetime import datetime, timezone
app_dir, node_data, ovpn_root, backup_root, node, from_version = sys.argv[1:]
members = {}
def add_tree(archive, src, arc):
    for root, _dirs, files in os.walk(src):
        for name in sorted(files):
            if name in ("update-maintenance", "update-state.json"):
                continue  # live transaction artifacts must never restore
            full = os.path.join(root, name)
            if not os.path.isfile(full) or os.path.islink(full) and not os.path.exists(full):
                continue
            rel = os.path.join(arc, os.path.relpath(full, src))
            archive.add(full, arcname=rel, recursive=False)
            digest = hashlib.sha256()
            with open(full, "rb") as f:
                for chunk in iter(lambda: f.read(1048576), b""):
                    digest.update(chunk)
            members[rel] = digest.hexdigest()
def add_file(archive, src, arc):
    if os.path.isfile(src):
        archive.add(src, arcname=arc, recursive=False)
        digest = hashlib.sha256()
        with open(src, "rb") as f:
            for chunk in iter(lambda: f.read(1048576), b""):
                digest.update(chunk)
        members[arc] = digest.hexdigest()
now = datetime.now(timezone.utc)
stamp = now.strftime("%Y%m%d_%H%M%S")
final = os.path.join(backup_root, "ovnode-state-pre-update-%s.tar.gz" % stamp)
fd, tmp = tempfile.mkstemp(prefix=".ovnode-state-", suffix=".part", dir=backup_root)
os.close(fd); os.chmod(tmp, 0o600)
try:
    with tempfile.TemporaryDirectory(prefix="ovnode-state-") as stage:
        with tarfile.open(tmp, "w:gz", format=tarfile.PAX_FORMAT) as archive:
            add_file(archive, os.path.join(app_dir, ".env"), "node.env")
            add_tree(archive, node_data, "data")
            for sub in ("server", "ccd", "ovnode"):
                add_tree(archive, os.path.join(ovpn_root, sub), "openvpn/%s" % sub)
            try:
                with open(os.path.join(app_dir, ".env"), encoding="utf-8") as f:
                    env = dict(line.strip().split("=", 1) for line in f if "=" in line and not line.startswith("#"))
                for key in ("SSL_KEYFILE", "SSL_CERTFILE"):
                    target = env.get(key, "")
                    if target and os.path.isfile(target):
                        add_file(archive, target, "tls/%s" % os.path.basename(target))
            except OSError:
                pass
            manifest = {"format": "ovnode-state", "format_version": 1, "node": node,
                        "from_version": from_version, "created_at": now.isoformat(), "members": members}
            manifest_path = os.path.join(stage, "manifest.json")
            with open(manifest_path, "w", encoding="utf-8") as f:
                json.dump(manifest, f, sort_keys=True, indent=2); f.write("\n")
            archive.add(manifest_path, arcname="manifest.json", recursive=False)
        with tarfile.open(tmp, "r:gz") as archive:
            names = {m.name for m in archive.getmembers() if m.isfile()}
            if "manifest.json" not in names:
                raise SystemExit("bundle verification failed: no manifest")
            if any(n.startswith("/") or ".." in n.split("/") for n in names):
                raise SystemExit("bundle verification failed: unsafe member")
            seen = json.load(archive.extractfile("manifest.json"))
            if seen.get("format") != "ovnode-state":
                raise SystemExit("bundle verification failed: bad manifest")
    os.replace(tmp, final); os.chmod(final, 0o600)
finally:
    try: os.unlink(tmp)
    except FileNotFoundError: pass
print(final)
PY
    # Retention for safety bundles (backup pruning covers node-*/node-pki-*).
    ls -t "$backup_root"/ovnode-state-pre-update-*.tar.gz 2>/dev/null | tail -n +6 | xargs -r rm -f
    return 0
}

# Restore verified state after a failed activation. Fails closed on any
# manifest/checksum problem; never extracts unsafe member names.
state_restore() {
    local bundle="$1"
    [[ -f "$bundle" ]] || return 1
    python3 - "$bundle" "$APP_DIR" "$DATA_BASE" "$OPENVPN_ROOT" <<'PY' || return 1
import hashlib, json, os, sys, tarfile, tempfile
bundle, app_dir, data_base, ovpn_root = sys.argv[1:]
roots = {"node.env": app_dir, "data/": data_base, "openvpn/": ovpn_root, "tls/": None, "manifest.json": None}
with tarfile.open(bundle, "r:gz") as archive:
    infos = [m for m in archive.getmembers() if m.isfile()]
    names = {m.name for m in infos}
    if "manifest.json" not in names:
        raise SystemExit("unsafe state backup: no manifest")
    if any(n.startswith("/") or ".." in n.split("/") for n in names):
        raise SystemExit("unsafe state backup: unsafe member")
    manifest = json.load(archive.extractfile("manifest.json"))
    if manifest.get("format") != "ovnode-state":
        raise SystemExit("unsafe state backup: bad manifest")
    expected = manifest.get("members", {})
    staged = tempfile.mkdtemp(prefix="ovnode-restore-")
    try:
        archive.extractall(path=staged, members=infos)
        for rel, digest in expected.items():
            with open(os.path.join(staged, rel), "rb") as f:
                actual = hashlib.sha256(f.read()).hexdigest()
            if actual != digest:
                raise SystemExit("state backup checksum mismatch: %s" % rel)
        import shutil
        for rel in expected:
            if rel == "node.env":
                dst = os.path.join(app_dir, ".env")
            elif rel.startswith("data/"):
                dst = os.path.join(data_base, os.path.relpath(rel, "data"))
            elif rel.startswith("openvpn/"):
                dst = os.path.join(ovpn_root, os.path.relpath(rel, "openvpn"))
            elif rel.startswith("tls/"):
                continue  # certs restore via repair flow, never auto-overwritten
            else:
                raise SystemExit("unsafe state backup: unknown member %s" % rel)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            fd, tmp = tempfile.mkstemp(prefix=".ovnode-restore-", dir=os.path.dirname(dst))
            try:
                with os.fdopen(fd, "wb") as f, open(os.path.join(staged, rel), "rb") as s:
                    shutil.copyfileobj(s, f, 1048576)
                if dst.endswith(".env"):
                    os.chmod(tmp, 0o600)
                os.replace(tmp, dst)
            finally:
                try: os.unlink(tmp)
                except FileNotFoundError: pass
    finally:
        shutil.rmtree(staged, ignore_errors=True)
print("state restored")
PY
}

# Authenticated status from the running agent: "version openvpn_running".
# Empty output means unreachable or rejected (identity broken).
node_api_status() {
    local key="$1" port="$2" tls="$3" scheme="http"
    [[ "$tls" != "none" ]] && scheme="https"
    curl -fskS --max-time 5 "${scheme}://127.0.0.1:${port}/sync/status" \
        -H "key: ${key}" 2>/dev/null \
        | python3 -c 'import json,sys; d=(json.load(sys.stdin).get("data") or {}); print(d.get("version",""), str(d.get("openvpn_running","")).lower())' 2>/dev/null || true
}

write_env() {
    # Note: TUNNEL_ADDRESS is intentionally NOT written here — the node's
    # pydantic Settings rejects extra env fields, and the panel pushes the
    # tunnel address via /sync/config when the node is added/updated.
    cat > "$APP_DIR/.env" << EOF
NODE_NAME=${NODE_NAME}
DATA_DIR=${DATA_BASE}/${NODE_NAME}
SERVICE_PORT=${PORT}
API_KEY=${API_KEY}
OPENVPN_PORT=${VPN_PORT}
OVNODE_PROTO=${VPN_PROTO:-tcp}
TLS_METHOD=${TLS_METHOD}
$( if [[ -n "$EXTRA_PORTS" ]]; then echo "OVNODE_EXTRA_PORTS=${EXTRA_PORTS}"; fi )
$( if [[ "$IPV6" -eq 1 ]]; then echo "OVNODE_ENABLE_IPV6=1"; fi )
$( if [[ -n "$TLS_KEY" ]]; then echo "SSL_KEYFILE=${TLS_KEY}"; fi )
$( if [[ -n "$TLS_CERT" ]]; then echo "SSL_CERTFILE=${TLS_CERT}"; fi )
EOF
    chmod 600 "$APP_DIR/.env"
    step ".env written"
}

# ── Docker ─────────────────────────────────────────────────────────────

ensure_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        info "Installing Docker Engine..."
        if [[ "$PKG_INSTALL" == apt* ]]; then
            $PKG_UPDATE >/dev/null 2>&1 || true
            $PKG_INSTALL docker.io >/dev/null 2>&1 \
                || $PKG_INSTALL docker-ce >/dev/null 2>&1 \
                || die "Could not install Docker via apt. Install manually: https://docs.docker.com/engine/install/"
        else
            pkg_install docker docker-compose-plugin >/dev/null 2>&1 || pkg_install docker
        fi
        command -v docker >/dev/null 2>&1 || die "Docker binary not found"
    fi
    docker compose version >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1 \
        || die "Docker Compose v2 is required (docker compose plugin)"
    step "Docker present"
}

setup_docker() {
    ensure_docker

    # The image's entrypoint runs OpenVPN inside the container; the host
    # only needs the tun module loaded and the device node present.
    modprobe tun >/dev/null 2>&1 || true
    if [[ ! -c /dev/net/tun ]]; then
        mkdir -p /dev/net && mknod /dev/net/tun c 10 200 2>/dev/null || true
    fi
    [[ -c /dev/net/tun ]] || warn "/dev/net/tun missing — the VPN cannot start until the tun module is available"

    write_compose_file

    run "Pulling published OVNode image" \
        docker pull "${IMAGE_REPO}:${IMAGE_TAG:-$VERSION}"
    run "Starting container" \
        docker compose -f "$(compose_file)" up -d
}

# Write the compose file pinning the exact published image. IMAGE_TAG
# overrides VERSION so updates and failovers can target a specific release.
# Never builds locally: Docker installs consume published images only.
write_compose_file() {
    local compose tag
    compose="$(compose_file)"
    tag="${IMAGE_TAG:-$VERSION}"
    mkdir -p "$DATA_BASE/$NODE_NAME"

    # TLS material lives on host paths (letsencrypt/self-signed/custom) —
    # mount them read-only or the agent cannot serve HTTPS. Let's Encrypt
    # needs the whole tree: live/ contains symlinks into archive/.
    local tls_mounts="" d f
    for f in "$TLS_KEY" "$TLS_CERT"; do
        [[ -n "$f" ]] || continue
        case "$f" in
            /etc/letsencrypt/*) d="/etc/letsencrypt" ;;
            *) d="$(dirname "$f")" ;;
        esac
        [[ "$tls_mounts" == *"- ${d}:${d}:ro"* ]] || tls_mounts+="      - ${d}:${d}:ro"$'\n'
    done

    cat > "$compose" << COMPOSE
services:
  ovnode:
    image: ${IMAGE_REPO}:${tag}
    container_name: ovnode-${NODE_NAME}
    restart: unless-stopped
    network_mode: host
    environment:
      SERVICE_PORT: ${PORT}
      API_KEY: ${API_KEY}
      DATA_DIR: /app/data
      OPENVPN_PORT: ${VPN_PORT}
      TLS_METHOD: ${TLS_METHOD}
      OVNODE_OPENVPN_ROOT: /etc/openvpn
$( if [[ -n "$EXTRA_PORTS" ]]; then echo "      OVNODE_EXTRA_PORTS: \"${EXTRA_PORTS}\""; fi )
$( if [[ "$IPV6" -eq 1 ]]; then echo "      OVNODE_ENABLE_IPV6: 1"; fi )
$( [[ -n "$TLS_KEY" ]] && echo "      SSL_KEYFILE: ${TLS_KEY}" )
$( [[ -n "$TLS_CERT" ]] && echo "      SSL_CERTFILE: ${TLS_CERT}" )
    volumes:
      - ${OPENVPN_ROOT}:/etc/openvpn
      - ${DATA_BASE}/${NODE_NAME}:/app/data
      - /dev/net/tun:/dev/net/tun
$( [[ -n "$tls_mounts" ]] && printf '%s' "$tls_mounts" )
    cap_add:
      - NET_ADMIN
    logging:
      options:
        max-size: "5m"
        max-file: "3"
COMPOSE
    # The compose file embeds the API key — keep it root-only, like .env.
    chmod 600 "$compose"
    step "Compose file written: $compose (image ${IMAGE_REPO}:${tag})"
}

# ── Install ────────────────────────────────────────────────────────────
do_install() {
    check_root
    check_deps
    [[ "$DOCKER" -eq 1 ]] || ensure_uv

    sep; info "Step 1/4 — Download verified release v${VERSION}"
    fetch_release "$APP_DIR"

    info "Step 2/4 — Certificate and configuration"
    if [[ "$DOCKER" -eq 0 ]]; then
        cd "$APP_DIR"
        run "Installing Python dependencies" uv_sync
    fi

    setup_tls
    write_env

    local scheme="http"
    [[ "$TLS_METHOD" != "none" ]] && scheme="https"
    local host; host="$(primary_ip)"

    mkdir -p "$DATA_BASE/$NODE_NAME"
    ensure_openvpn_dirs

    info "Step 3/4 — Runtime and service"
    if [[ "$DOCKER" -eq 1 ]]; then
        setup_docker
    else
        if ! has_systemd; then
            warn "systemd not found — start the agent manually: cd $APP_DIR && .venv/bin/python main.py"
        else
            write_systemd_unit
            run "Starting node agent service" systemctl_bounded restart "$SYSTEMD_SERVICE"
        fi
    fi

    # First boot generates the PKI + server.conf; wait for the agent to
    # answer /sync/health before bringing up OpenVPN so the config exists.
    info "Step 4/4 — Health check and finish"
    if ! wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 60; then
        warn "Agent did not answer /sync/health — check: journalctl -u $SYSTEMD_SERVICE -n 50"
    fi
    [[ "$DOCKER" -eq 1 ]] && check_container_openvpn

    # In Docker the OpenVPN daemon runs inside the container (supervised by
    # the entrypoint) — only manage it on the host for native installs.
    # Docker installs additionally evict a native daemon if one holds the
    # VPN/management ports on the shared host network namespace.
    if [[ "$DOCKER" -eq 0 ]]; then
        start_openvpn_service
    else
        stop_native_openvpn
    fi
    setup_nat
    setup_logrotate
    open_firewall_ports
    install_cli

    local tls_flag=0; [[ "$TLS_METHOD" != "none" ]] && tls_flag=1
    local bundle="ovnode://${NODE_NAME}@${host}:${PORT}?key=${API_KEY}&tls=${tls_flag}"
    line ""
    line "  ${GR}Ready — save this login${NC}"
    sep
    field "Node"        "${WH}${NODE_NAME}${NC}"
    field "Mode"        "$([ "$DOCKER" -eq 1 ] && echo Docker || echo Host)"
    field "Service"     "${WH}${scheme}://${host}:${PORT}${NC}"
    field "OpenVPN"     "$(vpn_ports_label)"
    local key_note="  ${GY}(the key you supplied)${NC}"
    if [[ "${KEY_GENERATED:-0}" -eq 1 ]]; then key_note="  ${GY}(generated — save this)${NC}"; fi
    field "API key"     "${GR}${API_KEY}${NC}${key_note}"
    field "Bundle"      "${CY}${bundle}${NC}"
    field "Manage"      "ovn  (status, credentials, logs, backup, TLS)"
    field "Data"        "$DATA_BASE/$NODE_NAME"
    field "OpenVPN cfg" "$OPENVPN_ROOT/server"
    line ""
    info "Add this node in the panel: Nodes → Add Node → paste the Bundle above"
    if [[ -n "$EXTRA_PORTS" ]]; then
        info "Clients get all VPN ports (${VPN_PORT},${EXTRA_PORTS}) in their .ovpn"
        info "and fail over automatically if one is blocked."
    fi
    # -q suppresses the card, but a credential nobody ever saw is a credential
    # lost. One line, carrying no secret, naming the recovery command.
    if [[ "$QUIET" -eq 1 ]]; then
        printf '  API key not shown (--quiet). Recover it with: ovn credentials\n' >&2
    fi
    line ""
}

# ── Update ─────────────────────────────────────────────────────────────
# Transactional: safety bundle + code snapshot, staged candidate, maintenance
# marker (mutating API calls blocked), atomic rename activation, verified
# commit or automatic failover. Identity (name + API key) is recovered from
# .env and never regenerated here.
do_update() {
    [[ -d "$APP_DIR" ]] || die "Not installed ($APP_DIR missing)" "$EX_NOTINSTALLED"
    check_root
    operation_begin update
    trap operation_end EXIT
    # Recover install parameters from the installed .env when not passed on
    # the CLI, so `update` never silently changes the configuration.
    local env_get; env_get() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true; }
    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(env_get NODE_NAME)"
    : "${NODE_NAME:=ovnode}"
    [[ -n "$PORT" ]] || PORT="$(env_get SERVICE_PORT)"
    : "${PORT:=$DEFAULT_PORT}"
    [[ -n "$API_KEY" ]] || API_KEY="$(env_get API_KEY)"
    [[ -n "$API_KEY" ]] || die "Installed .env has no API key — refusing to rotate identity (restore .env or reinstall)" "$EX_ERROR"
    if [[ -z "$VPN_PORTS" ]]; then
        VPN_PORT="$(env_get OPENVPN_PORT)"; : "${VPN_PORT:=$DEFAULT_VPN}"
        EXTRA_PORTS="$(env_get OVNODE_EXTRA_PORTS)"
    else
        parse_vpn_ports
    fi
    # Update keeps the install's existing TLS mode: read it from .env unless
    # the caller passed --tls / OVN_TLS. (Legacy nodes may legitimately have
    # "none" recorded; that still works — only new installs reject it.)
    if [[ "$CLI_FLAGS" -eq 0 && -z "${OVN_TLS:-}" ]]; then
        TLS_METHOD="$(env_get TLS_METHOD)"
    fi
    : "${TLS_METHOD:=selfsigned}"
    # Compose regeneration (docker) and setup steps need the full install
    # parameters: recover everything the update did not receive as flags so
    # a refresh never silently drops TLS mounts, extra ports or IPv6.
    [[ -n "$TLS_KEY" ]] || TLS_KEY="$(env_get SSL_KEYFILE)"
    [[ -n "$TLS_CERT" ]] || TLS_CERT="$(env_get SSL_CERTFILE)"
    if [[ -z "${OVN_IPV6:-}" && "$IPV6" -eq 0 ]]; then
        [[ "$(env_get OVNODE_ENABLE_IPV6)" == "1" ]] && IPV6=1
    fi

    line ""; info "Updating OVNode to v${VERSION}…"
    detect_os
    # Auto-detect the deployment mode: a compose file means this install was
    # done with --docker, even when `update` is called without the flag.
    if [[ -f "$(compose_file)" ]]; then
        DOCKER=1
        info "Detected Docker deployment (compose file present)"
    fi
    local from_version safety snapshot scheme activated=0 identity
    from_version="$(grep -Eo '"[0-9]+\.[0-9]+\.[0-9]+"' "$APP_DIR/core/version.py" 2>/dev/null | head -1 | tr -d '"' || true)"
    : "${from_version:=unknown}"
    identity="$(identity_sha "$NODE_NAME" "$API_KEY")"
    scheme="http"; [[ "$TLS_METHOD" != "none" ]] && scheme="https"
    update_state preflight "$from_version" "$VERSION" "" "$identity"

    info "Step 1/6 — Verified safety snapshot"
    safety="$(state_safety_bundle "$from_version")" || die "Could not create the mandatory state safety snapshot" "$EX_ERROR"
    [[ -n "$safety" && -f "$safety" ]] || die "The state safety snapshot was not created" "$EX_ERROR"
    snapshot="$(snapshot_code "$APP_DIR" "node" 2)"
    update_state staging "$from_version" "$VERSION" "$safety" "$identity"

    info "Step 2/6 — Stage verified release"
    rm -rf "$UPDATE_STAGE"
    mkdir -p "$UPDATE_STAGE"
    if [[ "$DOCKER" -eq 1 ]]; then
        ensure_docker
        run "Pulling published OVNode image" \
            docker pull "ghcr.io/${REPO,,}:${VERSION}" \
            || die "Could not pull ghcr.io/${REPO,,}:${VERSION}" "$EX_ERROR"
    else
        fetch_release "$UPDATE_STAGE"
        cp -p "$APP_DIR/.env" "$UPDATE_STAGE/.env" || die "Could not preserve configuration" "$EX_ERROR"
        chmod 600 "$UPDATE_STAGE/.env"
        ensure_uv
        ( cd "$UPDATE_STAGE" && run "Staged Python dependencies" uv_sync ) \
            || die "Could not prepare the staged release; current version is still running" "$EX_ERROR"
        [[ -f "$UPDATE_STAGE/core/version.py" ]] || die "Staged release is incomplete" "$EX_ERROR"
    fi

    info "Step 3/6 — Enter maintenance mode"
    : > "$(update_marker)"
    chmod 600 "$(update_marker)"
    update_state activating "$from_version" "$VERSION" "$safety" "$identity"
    if [[ "$DOCKER" -eq 1 ]]; then
        ( cd "$APP_DIR" && docker compose -f "$(compose_file)" down ) >/dev/null 2>&1 || true
    else
        # The OpenVPN daemon keeps serving clients; only the agent stops.
        systemctl_bounded stop "$SYSTEMD_SERVICE" >/dev/null 2>&1 || true
    fi

    info "Step 4/6 — Activate candidate"
    if [[ "$DOCKER" -eq 1 ]]; then
        IMAGE_TAG="$VERSION" write_compose_file
        ( cd "$APP_DIR" && docker compose -f "$(compose_file)" up -d ) >/dev/null 2>&1 \
            || { update_state recovery_required "$from_version" "$VERSION" "$safety" "$identity"; die "Could not start the candidate container. Writes remain blocked; run: ovn recover-update" "$EX_ERROR"; }
        activated=1
    else
        rm -rf "$UPDATE_PREVIOUS"
        if mv "$APP_DIR" "$UPDATE_PREVIOUS" && mv "$UPDATE_STAGE" "$APP_DIR"; then
            activated=1
        else
            if [[ -d "$APP_DIR" ]] || { [[ -d "$UPDATE_PREVIOUS" ]] && mv "$UPDATE_PREVIOUS" "$APP_DIR"; }; then
                rm -f "$(update_marker)"
                update_state failed_over "$from_version" "$VERSION" "$safety" "$identity"
                operation_end
                die "Could not activate the staged release; the previous release remains active and state was not changed" "$EX_ERROR"
            fi
            update_state recovery_required "$from_version" "$VERSION" "$safety" "$identity"
            operation_end
            die "Could not activate or restore release files. Writes remain blocked; run: ovn recover-update" "$EX_ERROR"
        fi
    fi

    local start_ok=0
    if [[ "$DOCKER" -eq 1 ]]; then
        start_ok=1
    else
        has_systemd && write_systemd_unit
        run "Candidate agent started" systemctl_bounded restart "$SYSTEMD_SERVICE" && start_ok=1 || true
    fi

    info "Step 5/6 — Verify candidate"
    update_state verifying "$from_version" "$VERSION" "$safety" "$identity"
    if [[ "$start_ok" -eq 1 ]] && wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 60; then
        local reported vpn_ok ident_ok
        read -r reported vpn_ok < <(node_api_status "$API_KEY" "$PORT" "$TLS_METHOD") || true
        ident_ok="$(identity_sha "$(env_get_after NODE_NAME)" "$(env_get_after API_KEY)")"
        if [[ "$reported" == "$VERSION" && "$vpn_ok" == "true" && "$ident_ok" == "$identity" ]]; then
            start_ok=1
        else
            warn "Candidate verification mismatch (version='${reported:-unknown}' openvpn='${vpn_ok:-unknown}' identity-preserved=$([[ "$ident_ok" == "$identity" ]] && echo yes || echo no))"
            start_ok=0
        fi
    else
        start_ok=0
    fi

    if [[ "$start_ok" -ne 1 ]]; then
        warn "Candidate verification failed — failing over to v${from_version}"
        update_state failing_over "$from_version" "$VERSION" "$safety" "$identity"
        node_failover "$from_version" "$VERSION" "$safety" "$identity" "$snapshot"
    fi

    info "Step 6/6 — Commit update"
    rm -f "$(update_marker)"
    if [[ "$DOCKER" -eq 0 ]]; then
        setup_nat
        setup_logrotate
    fi
    if ! wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 60; then
        : > "$(update_marker)"; chmod 600 "$(update_marker)"
        update_state recovery_required "$from_version" "$VERSION" "$safety" "$identity"
        operation_end
        die "Candidate passed verification but failed its final check. Writes are blocked; run: ovn recover-update" "$EX_ERROR"
    fi
    update_state committed "$from_version" "$VERSION" "$safety" "$identity"
    operation_end
    install_cli
    step "Update complete  v${from_version} → v${VERSION}"
    [[ "$DOCKER" -eq 1 ]] || step "Failover release kept at $UPDATE_PREVIOUS"
    line ""
}

# Read a key from the CURRENT (possibly just activated) install .env.
env_get_after() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true; }

# Failover to the pre-update release + state. Never returns on success paths
# (dies after journaling the terminal state).
node_failover() {
    local from_version="$1" target="$2" safety="$3" identity="$4" snapshot="$5"
    if [[ "$DOCKER" -eq 1 ]]; then
        ( cd "$APP_DIR" && docker compose -f "$(compose_file)" down ) >/dev/null 2>&1 || true
        state_restore "$safety" \
            || { update_state recovery_required "$from_version" "$target" "$safety" "$identity"; operation_end; die "Previous container stopped but state could not be restored. Run: ovn recover-update" "$EX_ERROR"; }
        IMAGE_TAG="$from_version" write_compose_file
        ( cd "$APP_DIR" && docker compose -f "$(compose_file)" up -d ) >/dev/null 2>&1 \
            || { update_state recovery_required "$from_version" "$target" "$safety" "$identity"; operation_end; die "Previous image could not be restarted. Run: ovn recover-update" "$EX_ERROR"; }
    else
        systemctl_bounded stop "$SYSTEMD_SERVICE" >/dev/null 2>&1 || true
        rm -rf "$UPDATE_STAGE"
        mv "$APP_DIR" "$UPDATE_STAGE" || true
        mv "$UPDATE_PREVIOUS" "$APP_DIR" \
            || { update_state recovery_required "$from_version" "$target" "$safety" "$identity"; operation_end; die "Automatic failover could not restore the previous release. Snapshot: $snapshot" "$EX_ERROR"; }
        state_restore "$safety" \
            || { update_state recovery_required "$from_version" "$target" "$safety" "$identity"; operation_end; die "Previous code was restored but state could not be restored" "$EX_ERROR"; }
        run "Previous agent restarted" systemctl_bounded restart "$SYSTEMD_SERVICE" \
            || { update_state recovery_required "$from_version" "$target" "$safety" "$identity"; operation_end; die "Previous release restored but will not start" "$EX_ERROR"; }
    fi
    local scheme="http"; [[ "$TLS_METHOD" != "none" ]] && scheme="https"
    if wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 60; then
        rm -f "$(update_marker)"
        update_state failed_over "$from_version" "$target" "$safety" "$identity"
        operation_end
        die "Update failed over safely to v${from_version}. State was restored from $safety. Check logs before retrying." "$EX_ERROR"
    fi
    update_state recovery_required "$from_version" "$target" "$safety" "$identity"
    operation_end
    die "Failover did not restore health either — state backup at $safety, code snapshot at $snapshot. Check logs." "$EX_ERROR"
}

# ── Uninstall ──────────────────────────────────────────────────────────
do_recover_update() {
    if [[ ! -f "$UPDATE_STATE" ]]; then
        [[ -f "$(update_marker)" ]] && die "Update maintenance marker exists but its state journal is missing" "$EX_ERROR"
        step "No interrupted update needs recovery"
        return 0
    fi
    local phase from target safety identity
    read -r phase from target safety identity < <(python3 - "$UPDATE_STATE" <<'PY'
import json, sys
x = json.load(open(sys.argv[1]))
print(x.get("phase", "unknown"), x.get("from_version", "unknown"),
      x.get("to_version", "unknown"), x.get("safety_backup") or "", x.get("identity_sha") or "")
PY
) || die "Update state journal is unreadable" "$EX_ERROR"
    case "$phase" in
        committed|failed_over)
            if [[ ! -f "$(update_marker)" ]]; then
                step "No interrupted update needs recovery"
                return 0
            fi
            ;;
        preflight|staging)
            # Activation had not begun: installed release and state are
            # untouched. Discard staging and clear the journal.
            check_root
            operation_begin recover-update
            trap operation_end EXIT
            rm -rf "$UPDATE_STAGE"
            rm -f "$(update_marker)"
            update_state failed_over "$from" "$target" "$safety" "$identity"
            operation_end
            step "Cleared an interrupted pre-activation update; v${from} remains active"
            return 0
            ;;
        activating|verifying|failing_over|recovery_required) ;;
        *) die "Update journal has unknown phase '$phase'; writes remain blocked" "$EX_ERROR" ;;
    esac
    check_root
    operation_begin recover-update
    trap operation_end EXIT
    if [[ ! -f "$(update_marker)" ]]; then
        : > "$(update_marker)"
        chmod 600 "$(update_marker)"
        warn "Re-created the missing update maintenance marker"
    fi
    [[ -f "$(compose_file)" ]] && DOCKER=1 || DOCKER=0
    local env_get; env_get() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true; }
    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(env_get NODE_NAME)"
    : "${NODE_NAME:=ovnode}"
    [[ -n "$PORT" ]] || PORT="$(env_get SERVICE_PORT)"
    : "${PORT:=$DEFAULT_PORT}"
    local api_key
    api_key="$(env_get API_KEY)"
    [[ -n "$api_key" ]] || die "Installed .env has no API key — cannot verify identity. Restore .env from $safety, then retry." "$EX_ERROR"
    TLS_METHOD="$(env_get TLS_METHOD)"; : "${TLS_METHOD:=selfsigned}"
    local scheme="http"; [[ "$TLS_METHOD" != "none" ]] && scheme="https"
    local reported vpn_ok ident_ok
    if wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 5; then
        read -r reported vpn_ok < <(node_api_status "$api_key" "$PORT" "$TLS_METHOD") || true
        ident_ok="$(identity_sha "$(env_get NODE_NAME)" "$api_key")"
    fi
    if [[ "${reported:-}" == "$target" && "${vpn_ok:-}" == "true" && "${ident_ok:-}" == "$identity" ]]; then
        rm -f "$(update_marker)"
        update_state committed "$from" "$target" "$safety" "$identity"
        operation_end
        step "Recovered update journal — v${target} is healthy"
        return 0
    fi
    if [[ "${reported:-}" == "$from" && "${vpn_ok:-}" == "true" && "${ident_ok:-}" == "$identity" && ! -d "$UPDATE_PREVIOUS" ]]; then
        rm -f "$(update_marker)"
        update_state failed_over "$from" "$target" "$safety" "$identity"
        operation_end
        step "Recovered update journal — previous v${from} is healthy"
        return 0
    fi
    if [[ ! -d "$UPDATE_PREVIOUS" ]]; then
        # Activation never swapped the trees: restart the intact install.
        rm -rf "$UPDATE_STAGE"
        if [[ "$DOCKER" -eq 1 ]]; then
            ( cd "$APP_DIR" && docker compose -f "$(compose_file)" up -d ) >/dev/null 2>&1 || true
        else
            systemctl_bounded restart "$SYSTEMD_SERVICE" >/dev/null 2>&1 || systemctl start "$SYSTEMD_SERVICE" >/dev/null 2>&1 || true
        fi
        if wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 60; then
            rm -f "$(update_marker)"
            update_state failed_over "$from" "$target" "$safety" "$identity"
            operation_end
            step "Interrupted update never activated — v${from} restarted, staging discarded"
            return 0
        fi
        update_state recovery_required "$from" "$target" "$safety" "$identity"
        operation_end
        die "Interrupted update never activated and v${from} does not answer health. Run: ovn logs 100" "$EX_ERROR"
    fi
    info "Interrupted candidate is unhealthy — failing over to v${from}"
    if [[ "$DOCKER" -eq 1 ]]; then
        ( cd "$APP_DIR" && docker compose -f "$(compose_file)" down ) >/dev/null 2>&1 || true
        [[ -n "$safety" ]] && state_restore "$safety" \
            || die "Previous container stopped, but state could not be restored" "$EX_ERROR"
        IMAGE_TAG="$from" write_compose_file
        ( cd "$APP_DIR" && docker compose -f "$(compose_file)" up -d ) >/dev/null 2>&1 \
            || die "Previous image could not be restarted" "$EX_ERROR"
    else
        systemctl_bounded stop "$SYSTEMD_SERVICE" >/dev/null 2>&1 || true
        rm -rf "$UPDATE_STAGE"
        [[ -d "$APP_DIR" ]] && mv "$APP_DIR" "$UPDATE_STAGE"
        mv "$UPDATE_PREVIOUS" "$APP_DIR" || die "Could not restore the previous release directory" "$EX_ERROR"
        [[ -n "$safety" ]] && state_restore "$safety" \
            || die "Previous release restored, but state could not be restored" "$EX_ERROR"
        systemctl_bounded restart "$SYSTEMD_SERVICE" >/dev/null 2>&1 \
            || die "Previous release restored but will not start" "$EX_ERROR"
    fi
    if wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 60; then
        rm -f "$(update_marker)"
        update_state failed_over "$from" "$target" "$safety" "$identity"
        operation_end
        step "Interrupted update failed over safely to v${from}"
        return 0
    fi
    update_state recovery_required "$from" "$target" "$safety" "$identity"
    operation_end
    die "Previous release was restored but is not healthy. Run: ovn logs 100" "$EX_ERROR"
}

# Regenerate host integration files from the installed release + .env
# (unit, NAT, logrotate). Non-disruptive: no restart, no re-enrollment.
do_repair_unit() {
    [[ -d "$APP_DIR" ]] || die "Not installed ($APP_DIR missing)" "$EX_NOTINSTALLED"
    check_root
    operation_begin repair-unit
    trap operation_end EXIT
    local env_get; env_get() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true; }
    NODE_NAME="$(env_get NODE_NAME)"; : "${NODE_NAME:=ovnode}"
    PORT="$(env_get SERVICE_PORT)"; : "${PORT:=$DEFAULT_PORT}"
    API_KEY="$(env_get API_KEY)"
    [[ -n "$API_KEY" ]] || die "Installed .env has no API key — restore .env first" "$EX_ERROR"
    VPN_PORT="$(env_get OPENVPN_PORT)"; : "${VPN_PORT:=$DEFAULT_VPN}"
    EXTRA_PORTS="$(env_get OVNODE_EXTRA_PORTS)"
    TLS_METHOD="$(env_get TLS_METHOD)"; : "${TLS_METHOD:=selfsigned}"
    TLS_KEY="$(env_get SSL_KEYFILE)"; TLS_CERT="$(env_get SSL_CERTFILE)"
    [[ "$(env_get OVNODE_ENABLE_IPV6)" == "1" ]] && IPV6=1 || IPV6=0
    detect_os
    if [[ -f "$(compose_file)" ]]; then
        DOCKER=1
        ensure_docker
        write_compose_file
        step "Compose file regenerated (image ${IMAGE_REPO}:${IMAGE_TAG:-$VERSION})"
    else
        DOCKER=0
        has_systemd || die "systemd not found — cannot install the agent unit" "$EX_ERROR"
        write_systemd_unit
        setup_nat
        setup_logrotate
    fi
    operation_end
    step "Host integration repaired — restart the agent if it is stopped: ovn restart"
}

# ── Uninstall ──────────────────────────────────────────────────────────
do_uninstall() {
    [[ -d "$APP_DIR" ]] || die "Not installed ($APP_DIR missing)" "$EX_NOTINSTALLED"
    check_root
    operation_begin uninstall
    trap operation_end EXIT
    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(grep -E '^NODE_NAME=' "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true)"
    : "${NODE_NAME:=ovnode}"
    # Defaults to NO, matching OVManager. Removing a node is destructive and a
    # bare Enter should not do it; the -y path and --purge are unaffected.
    confirm "Remove OVNode and stop all services?" n || die "Cancelled."

    # Stopping the NAT unit runs its ExecStop cleanup (rules removed).
    systemctl_bounded stop "$SYSTEMD_SERVICE"
    systemctl_bounded stop "$NAT_SERVICE"
    systemctl_bounded stop openvpn-server@server
    systemctl disable "$SYSTEMD_SERVICE" "$NAT_SERVICE" openvpn-server@server 2>/dev/null || true
    rm -f "/etc/systemd/system/$SYSTEMD_SERVICE" "/etc/systemd/system/$NAT_SERVICE"
    systemctl daemon-reload 2>/dev/null || true

    if command -v docker >/dev/null 2>&1 && [[ -f "$(compose_file)" ]]; then
        ( cd "$APP_DIR" && docker compose -f "$(compose_file)" down ) >/dev/null 2>&1 || true
        docker rm -f "ovnode-$NODE_NAME" >/dev/null 2>&1 || true
    fi

    rm -f "$NAT_SCRIPT" "$NAT_CONF" "$SYSCTL_CONF" "$LOGROTATE_CONF"
    remove_cli
    close_firewall_ports
    rm -rf "$APP_DIR"
    if [[ "$PURGE" -eq 1 ]]; then
        backup_dir "$DATA_BASE" "node-pre-purge"
        rm -rf "$DATA_BASE"
        backup_dir "$OPENVPN_ROOT" "openvpn-pre-purge"
        rm -rf "$OPENVPN_ROOT"
        step "Data and OpenVPN configuration removed (backups in /var/backups)"
    else
        step "App removed. Data kept at $DATA_BASE and $OPENVPN_ROOT (use --purge to remove them too)"
    fi
    step "OVNode uninstalled"
    line ""
}

# ── Status ─────────────────────────────────────────────────────────────

# ── Interactive setup (humans on a TTY) ────────────────────────────────
interactive_setup() {
    local api_default
    api_default="$(openssl rand -hex 32)"
    line "${B}Step 1/4 — Node identity${NC}"
    NODE_NAME="$(ask "Node name" "${NODE_NAME:-ovnode}")"
    PORT="$(ask "Service port" "${PORT:-$(find_free_port "$DEFAULT_PORT")}")"
    VPN_PORTS="$(ask "OpenVPN port(s), comma sep." "${VPN_PORTS:-$DEFAULT_VPN}")"
    API_KEY="$(ask "API key (blank=generate)" "${API_KEY:-$api_default}")"

    # Transport: UDP is faster (no TCP-over-TCP meltdown); TCP only where
    # DPI/firewalls block UDP. Interactive default is UDP; unattended
    # installs stay on TCP (previous behavior, zero surprise).
    if [[ -z "$VPN_PROTO" ]]; then
        if is_tty && [[ "$YES" -eq 0 ]]; then
            line ""
            line "${B}Step 2/4 — VPN transport${NC}"
            line "  ${WH}1${NC})  UDP — faster, recommended"
            line "  ${WH}2${NC})  TCP — only where UDP is blocked"
            local proto_choice; proto_choice="$(ask "Transport" "1")"
            [[ "$proto_choice" == "2" ]] && VPN_PROTO="tcp" || VPN_PROTO="udp"
        else
            VPN_PROTO="tcp"
        fi
    fi

    if [[ "$DOCKER" -eq 0 ]]; then
        line ""
        line "${B}Step 3/4 — Deployment${NC}"
        line "  ${WH}1${NC})  Host — systemd service (recommended)"
        line "  ${WH}2${NC})  Docker — agent + OpenVPN in one container"
        local dep; dep="$(ask "Mode" "1")"
        [[ "$dep" == "2" ]] && DOCKER=1
    fi

    line ""
    line "${B}Step 4/4 — Certificate (always encrypted)${NC}"
    line "  ${WH}1${NC})  Self-signed (default)     encrypted; turn TLS *on* in the panel"
    line "  ${WH}2${NC})  Let's Encrypt (domain)    needs a domain pointed here + free port 80"
    line "  ${WH}3${NC})  Let's Encrypt (this IP)   short-lived cert, no domain needed"
    line "  ${WH}4${NC})  Custom cert path          bring your own key + cert files"
    local tls_choice
    tls_choice="$(ask "TLS mode" "1")"
    case "${tls_choice:-1}" in
        1) TLS_METHOD="selfsigned" ;;
        2) TLS_METHOD="letsencrypt"; TLS_DOMAIN="$(ask "Domain" "")"; [[ -n "$TLS_DOMAIN" ]] || die "Domain required for Let's Encrypt" ;;
        3) TLS_METHOD="letsencrypt-ip"; TLS_DOMAIN="$(primary_ip)" ;;
        4) TLS_METHOD="custom"; TLS_KEY="$(ask "Key file" "")"; TLS_CERT="$(ask "Cert file" "")" ;;
        *) TLS_METHOD="selfsigned" ;;
    esac
}

# Express install: safe defaults, no further questions. TLS is always on.
apply_express_defaults() {
    : "${PORT:=$(find_free_port "$DEFAULT_PORT")}"
    : "${VPN_PORTS:=$DEFAULT_VPN}"
    : "${NODE_NAME:=ovnode}"
    : "${VPN_PROTO:=udp}"
    TLS_METHOD="selfsigned"
    [[ -n "$API_KEY" ]] || generate_api_key
    EXPRESS=1
}

# Friendly front door: shown only for a bare interactive invocation.
# Host install is the default; Docker is the explicit second choice.
start_menu() {
    line "  ${B}OVNode Setup${NC}"
    sep
    line ""
    line "  ${GR}1.${NC} Install              ${GY}Recommended${NC}"
    line "  ${WH}2.${NC} Install with Docker"
    line ""
    line "  ${WH}0.${NC} Exit"
    line ""
    local choice
    choice="$(ask "Select" "1")"
    case "${choice:-1}" in
        1) apply_express_defaults ;;
        2) DOCKER=1; apply_express_defaults ;;
        0) line "Cancelled. No changes were made."; exit "$EX_OK" ;;
        *) warn "Choose 0, 1, or 2."; start_menu ;;
    esac
    line ""
}


# ── Terminal command (TUI) ─────────────────────────────────────────────
# install_cli() copies this installer to $BIN_DIR as "ovnode" (+ "ovn"), so a
# bare `ovnode` opens the menu. Every action is also a subcommand for scripts:
# status | start | stop | restart | restart-vpn | logs [N|-f] | backup |
# update | tls | uninstall | menu | help.

# systemd waits up to TimeoutStopSec for a stuck unit; bound the wait so an
# uninstall/update never looks frozen, then force the unit.
STOP_TIMEOUT="${OVN_STOP_TIMEOUT:-20}"





# Keep only the newest N tarballs this installer writes (/var/backups).

# Host-level daily backup: a systemd timer running `ovnode backup`.






installed_menu() {
    warn "OVNode is already installed"
    info "Manage the node with: ovn  (status, logs, backup, TLS)"
    while true; do
        local tag
        tag="$(tui_select "OVNode — installer" \
            update      "Update" \
            uninstall   "Uninstall" \
            quit        "Quit")"
        case "$tag" in
            update)      do_update || warn "Update failed" ;;
            uninstall)
                confirm_no "Also delete data and backups?" && PURGE=1
                do_uninstall
                return 0 ;;
            *)           return 0 ;;
        esac
    done
}

install_cli() {
    # The manager is the day-to-day command (ovnode/ovn). Refreshed on
    # every update, which auto-swaps boxes whose ovn is an old installer copy.
    local src="${APP_DIR}/manager.sh"
    [[ -f "$src" ]] || return 0
    mkdir -p "$BIN_DIR" 2>/dev/null || { warn "Could not create $BIN_DIR"; return 0; }
    if cp -f "$src" "$BIN_DIR/$CLI_NAME" 2>/dev/null && chmod 0755 "$BIN_DIR/$CLI_NAME"; then
        ln -sf "$CLI_NAME" "$BIN_DIR/$CLI_ALIAS" 2>/dev/null || true
        step "Command  ${BIN_DIR}/${CLI_NAME}  (alias: ${CLI_ALIAS})"
    else
        warn "Could not install the $CLI_NAME command into $BIN_DIR"
    fi
}

remove_cli() {
    rm -f "$BIN_DIR/$CLI_NAME" "$BIN_DIR/$CLI_ALIAS" 2>/dev/null || true
    # `ovn completion` writes this; leaving it behind completes a command
    # that no longer exists.
    rm -f "${OVN_COMPLETION_DIR:-/etc/bash_completion.d}/ovn" 2>/dev/null || true
}

# ── Preconditions ──────────────────────────────────────────────────────
check_deps() {
    local missing=() cmd
    for cmd in curl tar openssl git; do
        command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
    done
    # Native mode runs the agent + OpenVPN on the host; Docker bundles both
    # in the image, so the host needs neither python nor openvpn.
    if [[ "$DOCKER" -eq 0 ]]; then
        command -v python3 >/dev/null 2>&1 || missing+=("python3")
    fi
    [[ ${#missing[@]} -eq 0 ]] || pkg_install "${missing[@]}"
    if [[ "$DOCKER" -eq 0 ]] && ! command -v openvpn >/dev/null 2>&1; then
        info "Installing OpenVPN + easy-rsa (for client PKI)..."
        pkg_install openvpn easy-rsa
    fi
    step "System dependencies present"
}

# ── Main ───────────────────────────────────────────────────────────────
main() {
    parse_args "$@"
    [[ -n "${OVN_SRC:-}" && "${OVN_SRC}" != "release" ]] && die "Source installs were removed — the installer consumes verified releases only (developers: clone the repo)" "$EX_USAGE"
    [[ -n "${OVN_BRANCH:-}" ]] && die "OVN_BRANCH was removed with source installs — developers: git checkout the branch in a clone" "$EX_USAGE"
    case "$SRC" in
        release) ;;
        *) die "Invalid source '$SRC' (releases only)" "$EX_USAGE" ;;
    esac
    if [[ -n "$PIN" ]]; then
        valid_release_version "$PIN" \
            || die "Bad --version '$PIN' (use 1.2.3, v1.2.3, 1.2.3-rc1)" "$EX_USAGE"
        VERSION="${PIN#v}"
    fi
    if fancy; then command clear >/dev/null 2>&1 || true; fi
    # The tagline advertises a fresh install, so it must not appear on
    # update/uninstall/repair where it reads as if work were about to start.
    local subtitle
    case "$ACTION" in
        install) subtitle="Secure VPN node — up and running in a few minutes" ;;
        *)      subtitle="Secure VPN node" ;;
    esac
    line ""
    line "  ${B}OVNode installer${NC}  ${GY}v${VERSION}${NC}"
    line "  ${GY}${subtitle}${NC}"
    line ""

    case "$ACTION" in
        uninstall) do_uninstall; exit "$EX_OK" ;;
        update)    confirm "Update OVNode now?" || exit "$EX_OK"; do_update; exit "$EX_OK" ;;
        recover-update) do_recover_update; exit "$EX_OK" ;;
        repair-unit) do_repair_unit; exit "$EX_OK" ;;
        interactive) INTERACTIVE=1 ;;
    esac

    # Validation must precede the already-installed guard, otherwise a caller
    # invoking `install --port abc` gets exit 3 (Already installed) instead
    # of exit 2 with the usage message. When flags or OVN_* inputs are
    # present the values are checkable right away, even on an installed host.
    if [[ "$CLI_FLAGS" -eq 1 || "$ENV_INPUTS" -eq 1 ]]; then
        [[ -n "$PORT" ]]      || PORT="$DEFAULT_PORT"
        [[ -n "$TLS_METHOD" ]]|| TLS_METHOD="selfsigned"
        [[ -n "$VPN_PORTS" ]] || VPN_PORTS="$DEFAULT_VPN"
        [[ -n "$NODE_NAME" ]] || NODE_NAME="ovnode"
        validate_input
    fi

    # install
    if [[ -d "$APP_DIR" ]]; then
        if [[ "$YES" -eq 1 ]]; then
            die "Already installed ($APP_DIR exists). Run 'update' to refresh or 'uninstall' first." "$EX_ALREADY"
        fi
        installed_menu
        exit "$EX_OK"
    fi

    # Bare interactive invocation → friendly start menu (fresh installs only). Scripts/flags and
    # OVN_* env configuration keep the original machine path untouched.
    if [[ "$CMD_GIVEN" -eq 0 && "$CLI_FLAGS" -eq 0 && "$ENV_INPUTS" -eq 0 && "$YES" -eq 0 ]] && is_tty; then
        start_menu
    fi

    detect_os
    if [[ "${INTERACTIVE:-0}" -eq 1 ]] || { [[ "$YES" -eq 0 ]] && is_tty && [[ -z "$PORT" || -z "$API_KEY" ]]; }; then
        interactive_setup
    else
        : "${PORT:=$(find_free_port "$DEFAULT_PORT")}"
        : "${VPN_PORTS:=$DEFAULT_VPN}"
        : "${NODE_NAME:=ovnode}"
        : "${TLS_METHOD:=selfsigned}"
        : "${VPN_PROTO:=udp}"
        [[ -n "$API_KEY" ]] || generate_api_key
    fi
    validate_input

    field "OS"        "$OS_NAME"
    field "Version"   "v$VERSION (verified release)"
    field "Mode"      "$([ "$DOCKER" -eq 1 ] && echo Docker || echo Host)"
    field "Node"      "$NODE_NAME"
    field "Service"   "$PORT"
    field "OpenVPN"   "$(vpn_ports_label)/$VPN_PROTO"
    field "TLS"       "$TLS_METHOD"
    field "Install"   "$APP_DIR"
    field "Data"      "$DATA_BASE/$NODE_NAME"
    sep
    # No extra confirm: the review card above is the confirmation, same as
    # the panel installer.

    do_install
}

main "$@"
