#!/bin/bash
# Copyright (c) 2025 anonysec. All rights reserved.
# Proprietary and confidential. Unauthorized copying, distribution, or use is prohibited.
#
# ══════════════════════════════════════════════════════════════════════
#  OVNode — OpenVPN Node Agent Installer
#
#  Install :  bash <(curl -Ls https://anonysec.github.io/OVNode/install.sh)
#  Update  :  bash <(curl -Ls URL) update
#  Remove  :  bash <(curl -Ls URL) uninstall
#
#  Installs the agent (uv + systemd/Docker), scaffolds the OpenVPN server
#  (PKI is generated by the agent on first boot), enables NAT/masquerade so
#  client traffic can route through the node, redirects any extra VPN ports
#  to the OpenVPN daemon (multi-port anti-blocking), and verifies
#  /sync/health.
# ══════════════════════════════════════════════════════════════════════

set -Eeuo pipefail

# ── Config ─────────────────────────────────────────────────────────────
REPO="anonysec/OVNode"
BRANCH="main"
APP_DIR="/opt/ovnode"
DATA_BASE="/var/lib/ovnode"
OPENVPN_ROOT="/etc/openvpn"
DEFAULT_PORT=2083
DEFAULT_VPN=1194
SYSTEMD_SERVICE="ovnode.service"
NAT_SERVICE="ovnode-nat.service"
NAT_SCRIPT="/usr/local/sbin/ovnode-nat.sh"
NAT_CONF="/etc/default/ovnode-nat"
SYSCTL_CONF="/etc/sysctl.d/99-ovnode.conf"
LOGROTATE_CONF="/etc/logrotate.d/ovnode"
VERSION="3.0"

# ── Colors / UI ────────────────────────────────────────────────────────
NC=$'\033[0m'; B=$'\033[1m'; D=$'\033[2m'
WH=$'\033[97m'; GR=$'\033[32m'; RD=$'\033[31m'
YL=$'\033[33m'; CY=$'\033[36m'; GY=$'\033[90m'
[[ -t 1 ]] || { NC=''; B=''; D=''; WH=''; GR=''; RD=''; YL=''; CY=''; GY=''; }

line()  { echo -e "  $1" >&2; }
step()  { line "${GR}  ✓${NC} $1"; }
info()  { line "${CY}  →${NC} $1"; }
warn()  { line "${YL}  ⚠${NC} $1"; }
field() { printf "  ${GY}%-18s${NC} %s\n" "$1" "$2"; }
sep()   { line "${GY}$(printf '%.0s─' {1..56})${NC}"; }
die()   { echo -e "\n  ${RD}Error:${NC} $1\n" >&2; exit 1; }
trap 'echo -e "\n  ${RD}Interrupted.${NC}" >&2; exit 1' INT TERM

spinner() {
    local msg="$1" pid=$2 chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' i=0 rc=0
    while kill -0 "$pid" 2>/dev/null; do
        printf "\r  ${CY}%s${NC} %-46s" "${chars:$((i%9)):1}" "$msg" >&2
        sleep 0.1; i=$(( i + 1 ))
    done
    wait "$pid" 2>/dev/null || rc=$?
    printf "\r\033[K" >&2
    [[ $rc -eq 0 ]] && step "$msg" || { line "${RD}  ✗${NC} $msg"; return 1; }
}

is_tty() { [[ -t 0 ]]; }

ask() {
    local label="$1" default="$2" hidden="${3:-}" val=""
    if is_tty; then
        printf "  ${WH}%-24s${NC} ${GY}[%s]${NC} : " "$label" "$default"
        if [[ "$hidden" == "h" ]]; then read -rs val; printf "\n"; else read -r val; fi
    fi
    echo "${val:-$default}"
}

confirm() {
    [[ "$YES" -eq 1 ]] && return 0
    is_tty || return 0
    printf "  %s [${GR}Y${NC}/n] : " "$1"
    read -r c
    [[ ! "$c" =~ ^[Nn]$ ]]
}

# ── OS / package manager ───────────────────────────────────────────────
OS_ID="" OS_NAME="" PKG_INSTALL="" PKG_UPDATE=""

detect_os() {
    [[ -f /etc/os-release ]] || die "Unsupported OS — no /etc/os-release found."
    # shellcheck disable=SC1091
    . /etc/os-release
    OS_ID="${ID:-}"; OS_NAME="${PRETTY_NAME:-$OS_ID}"
    case "$OS_ID" in
        debian|ubuntu)      PKG_UPDATE="apt-get update -qq";  PKG_INSTALL="apt-get install -y -qq" ;;
        rhel|centos|rocky|almalinux|fedora)
            if command -v dnf >/dev/null 2>&1; then
                PKG_UPDATE="dnf -q makecache"; PKG_INSTALL="dnf install -y -q"
            else
                PKG_UPDATE="yum -q makecache"; PKG_INSTALL="yum install -y -q"
            fi ;;
        arch)               PKG_UPDATE="pacman -Sy --noconfirm"; PKG_INSTALL="pacman -S --noconfirm" ;;
        alpine)             PKG_UPDATE="apk update -q";          PKG_INSTALL="apk add -q" ;;
        *) die "Unsupported distribution: ${OS_ID:-unknown}" ;;
    esac
}

pkg_install() {
    info "Installing: $*"
    $PKG_UPDATE >/dev/null 2>&1 || true
    $PKG_INSTALL "$@" >/dev/null 2>&1 || die "Failed to install: $*"
}

has_systemd() { command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; }

# ── Args ───────────────────────────────────────────────────────────────
PORT="" API_KEY="" VPN_PORTS="" NODE_NAME=""
TLS_METHOD="none" TLS_DOMAIN="" TLS_KEY="" TLS_CERT=""
DOCKER=0 ACTION="install" YES=0 PURGE=0 NO_NAT=0 IPV6=0
# Derived from VPN_PORTS by validate_input:
VPN_PORT="" EXTRA_PORTS=""

show_help() {
    cat << 'EOF'
  Usage:
    bash <(curl -Ls https://anonysec.github.io/OVNode/install.sh)
    bash <(curl -Ls URL) update
    bash <(curl -Ls URL) uninstall

  Commands:
    (none)              Install OVNode
    update              Pull latest changes and restart (with backup)
    uninstall           Remove OVNode (data kept unless --purge)

  Flags:
    --port PORT         Service port (default: 2083)
    --api-key KEY       API key (min 16 chars; auto-generated if empty)
    --vpn-ports LIST    OpenVPN ports, comma separated (default: 1194).
                        The first port is the OpenVPN listener; the rest
                        are redirected to it (iptables) and included in
                        every .ovpn so clients fail over when an ISP
                        blocks a port. Example: --vpn-ports 1194,443,8443
    --vpn-port PORT     Shorthand for a single-port setup
    --name NAME         Node name (default: node-1)
    --tls METHOD        letsencrypt | letsencrypt-ip | selfsigned | custom | none
    --tls-domain DOM    Domain or IP for Let's Encrypt
    --tls-key K         Key file (with --tls custom)
    --tls-cert C        Cert file (with --tls custom)
    --docker            Run inside Docker (host networking, built from source)
    --ipv6              Enable IPv6 (ULA pool + route push) on the VPN
    --no-nat            Skip IP forwarding + NAT masquerade + port redirects
    --yes  | -y         Non-interactive: accept defaults, skip confirmations
    --purge             With uninstall: also remove data and OpenVPN config
    --help | -h         Show this help
EOF
    exit 0
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --port)       [[ $# -ge 2 ]] || die "--port needs a value"; PORT="$2"; shift 2 ;;
            --api-key)    [[ $# -ge 2 ]] || die "--api-key needs a value"; API_KEY="$2"; shift 2 ;;
            --vpn-ports)  [[ $# -ge 2 ]] || die "--vpn-ports needs a value"; VPN_PORTS="$2"; shift 2 ;;
            --vpn-port)   [[ $# -ge 2 ]] || die "--vpn-port needs a value"; VPN_PORTS="$2"; shift 2 ;;
            --name)       [[ $# -ge 2 ]] || die "--name needs a value"; NODE_NAME="$2"; shift 2 ;;
            --tls)        [[ $# -ge 2 ]] || die "--tls needs a value"; TLS_METHOD="$2"; shift 2 ;;
            --tls-domain) [[ $# -ge 2 ]] || die "--tls-domain needs a value"; TLS_DOMAIN="$2"; shift 2 ;;
            --tls-key)    [[ $# -ge 2 ]] || die "--tls-key needs a value"; TLS_KEY="$2"; shift 2 ;;
            --tls-cert)   [[ $# -ge 2 ]] || die "--tls-cert needs a value"; TLS_CERT="$2"; shift 2 ;;
            --ipv6)       IPV6=1; shift ;;
            --docker)     DOCKER=1; shift ;;
            --no-nat)     NO_NAT=1; shift ;;
            --yes|-y)     YES=1; shift ;;
            --purge)      PURGE=1; shift ;;
            --uninstall)  ACTION="uninstall"; shift ;;
            --help|-h)    show_help ;;
            update)       ACTION="update"; shift ;;
            uninstall)    ACTION="uninstall"; shift ;;
            *)            die "Unknown option: $1 (--help for usage)" ;;
        esac
    done
}

# ── Validation ─────────────────────────────────────────────────────────
is_port() { [[ "$1" =~ ^[0-9]+$ ]] && (( $1 >= 1 && $1 <= 65535 )); }

# Splits VPN_PORTS ("1194,443,8443") into VPN_PORT (primary listener) and
# EXTRA_PORTS (comma separated, redirected to the primary).
parse_vpn_ports() {
    local raw="${VPN_PORTS:-$DEFAULT_VPN}" seen=" " port
    VPN_PORT="" EXTRA_PORTS=""
    IFS=',' read -ra _ports <<< "${raw// /}"
    for port in "${_ports[@]}"; do
        [[ -z "$port" ]] && continue
        is_port "$port" || die "Invalid OpenVPN port: '$port'"
        [[ "$seen" == *" $port "* ]] && continue
        seen+="$port "
        if [[ -z "$VPN_PORT" ]]; then
            VPN_PORT="$port"
        else
            EXTRA_PORTS="${EXTRA_PORTS:+$EXTRA_PORTS,}$port"
        fi
    done
    [[ -n "$VPN_PORT" ]] || die "At least one OpenVPN port is required"
}

validate_input() {
    is_port "$PORT" || die "Invalid service port: '$PORT'"
    parse_vpn_ports
    [[ "$VPN_PORT" == "$PORT" ]] && die "OpenVPN port and service port must differ"
    [[ -n "$NODE_NAME" ]] || NODE_NAME="node-1"
    [[ "$NODE_NAME" =~ ^[A-Za-z0-9_-]{1,64}$ ]] || die "Invalid node name"
    [[ -n "$API_KEY" ]] || die "API key is required (--api-key, or interactive install auto-generates one)"
    [[ ${#API_KEY} -ge 16 ]] || die "API key must be at least 16 characters (openssl rand -hex 32)"
    case "$TLS_METHOD" in
        letsencrypt|letsencrypt-ip|selfsigned|custom|none) ;;
        *) die "Invalid TLS method: '$TLS_METHOD'" ;;
    esac
    if [[ "$TLS_METHOD" == "letsencrypt" || "$TLS_METHOD" == "letsencrypt-ip" ]]; then
        [[ -n "$TLS_DOMAIN" ]] || die "--tls-domain is required for Let's Encrypt"
    fi
    if [[ "$TLS_METHOD" == "custom" ]]; then
        [[ -f "$TLS_KEY" && -f "$TLS_CERT" ]] || die "Custom TLS key/cert files not found"
    fi
}

port_in_use() { ss -ltn 2>/dev/null | awk -v p=":${1}$" '$4 ~ p {exit 0} END {exit 1}'; }

find_free_port() {
    local port="${1:-$DEFAULT_PORT}"
    while port_in_use "$port"; do ((port++)); done
    echo "$port"
}

vpn_ports_label() {
    if [[ -n "$EXTRA_PORTS" ]]; then
        echo "${VPN_PORT} (+ redirects: ${EXTRA_PORTS})"
    else
        echo "$VPN_PORT"
    fi
}

# ── Toolchain ──────────────────────────────────────────────────────────
ensure_uv() {
    if command -v uv >/dev/null 2>&1; then
        UV_BIN="$(command -v uv)"; step "uv found: $UV_BIN"; return
    fi
    info "Installing uv (Python package manager)..."
    curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null 2>&1 || \
        python3 -m pip install --quiet uv >/dev/null 2>&1 || \
        die "Could not install uv."
    UV_BIN="$(command -v uv 2>/dev/null || true)"
    [[ -n "$UV_BIN" ]] || UV_BIN="$HOME/.local/bin/uv"
    [[ -x "$UV_BIN" ]] || die "uv not found after install"
    step "uv installed: $UV_BIN"
}

# Reproducible dependency install: the lockfile pins exact versions.
# Fall back to a fresh resolve only when the lock cannot be honored.
uv_sync() {
    "$UV_BIN" sync --frozen --no-dev --quiet 2>/dev/null \
        || "$UV_BIN" sync --no-dev --quiet
}

# ── Backups ────────────────────────────────────────────────────────────
backup_dir() {
    local src="$1" label="$2"
    [[ -d "$src" ]] || return 0
    mkdir -p /var/backups
    local stamp; stamp="$(date +%Y%m%d-%H%M%S)"
    local base; base="$(basename "$src")"
    local file="/var/backups/${label}-${base}-${stamp}.tar.gz"
    info "Backing up ${label} data to $file ..."
    tar -czf "$file" -C "$(dirname "$src")" "$base" 2>/dev/null \
        || warn "Backup failed for $src — continuing anyway"
    step "Backup saved: $file"
}

# ── TLS ────────────────────────────────────────────────────────────────
generate_selfsigned() {
    info "Generating self-signed certificate..."
    mkdir -p /etc/ssl/self-signed
    local cn; cn="$(hostname -I 2>/dev/null | awk '{print $1}')"
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout /etc/ssl/self-signed/privkey.pem \
        -out /etc/ssl/self-signed/fullchain.pem \
        -subj "/C=US/ST=Local/L=Local/O=OVNode/CN=${cn}" >/dev/null 2>&1
    TLS_KEY="/etc/ssl/self-signed/privkey.pem"
    TLS_CERT="/etc/ssl/self-signed/fullchain.pem"
    step "Self-signed certificate generated"
}

ensure_acme() {
    if [[ ! -x "$HOME/.acme.sh/acme.sh" ]]; then
        info "Installing acme.sh..."
        curl -s https://get.acme.sh | sh >/dev/null 2>&1 || die "Failed to install acme.sh"
    fi
}

issue_letsencrypt() {
    local domain="$1" is_ip="$2"
    ensure_acme
    local email="acme-$(openssl rand -hex 4)@example.com"
    local outdir="/etc/letsencrypt/$domain"
    mkdir -p "$outdir"

    if [[ -f "$outdir/fullchain.pem" ]]; then
        local expiry days_left=0
        expiry="$(openssl x509 -enddate -noout -in "$outdir/fullchain.pem" 2>/dev/null | cut -d= -f2)"
        days_left=$(( ($(date -d "$expiry" +%s 2>/dev/null || echo 0) - $(date +%s)) / 86400 ))
        if (( days_left > 7 )); then
            step "Existing certificate valid for ${days_left} more days"
            TLS_KEY="$outdir/privkey.pem"; TLS_CERT="$outdir/fullchain.pem"
            return 0
        fi
        warn "Certificate expires soon (${days_left}d) — renewing..."
    fi

    local extra_args=()
    if [[ "$is_ip" == "1" ]]; then extra_args=(--certificate-profile shortlived --days 6); fi

    "$HOME/.acme.sh/acme.sh" --issue -d "$domain" --standalone "${extra_args[@]}" \
        --accountemail "$email" >/dev/null 2>&1 \
        || die "Failed to issue Let's Encrypt certificate for $domain"

    "$HOME/.acme.sh/acme.sh" --install-cert -d "$domain" \
        --key-file "$outdir/privkey.pem" \
        --fullchain-file "$outdir/fullchain.pem" \
        --reloadcmd "systemctl restart $SYSTEMD_SERVICE >/dev/null 2>&1 || true" >/dev/null 2>&1 \
        || die "Failed to install certificate to $outdir"
    TLS_KEY="$outdir/privkey.pem"; TLS_CERT="$outdir/fullchain.pem"
    step "Certificate installed to $outdir"
}

setup_tls() {
    case "$TLS_METHOD" in
        none) ;;
        selfsigned)     generate_selfsigned ;;
        letsencrypt)    issue_letsencrypt "$TLS_DOMAIN" "0" ;;
        letsencrypt-ip) issue_letsencrypt "$TLS_DOMAIN" "1" ;;
        custom)
            local out="/etc/letsencrypt/${TLS_DOMAIN:-node}"
            mkdir -p "$out"
            cp "$TLS_KEY" "$out/privkey.pem"
            cp "$TLS_CERT" "$out/fullchain.pem"
            TLS_KEY="$out/privkey.pem"; TLS_CERT="$out/fullchain.pem"
            ;;
    esac
}

# ── NAT / routing / multi-port redirects ───────────────────────────────
# One idempotent script owns every iptables rule OVNode needs:
#   * MASQUERADE so VPN clients can route through the uplink
#   * REDIRECT for each extra VPN port → the OpenVPN listener (both tcp
#     and udp, because the panel can switch the VPN protocol at any time)
# Ports are read from /etc/default/ovnode-nat so a port change only needs
# that file edited + `systemctl restart ovnode-nat`.
write_nat_files() {
    cat > "$SYSCTL_CONF" << 'SYSCTL'
# OVNode: allow OpenVPN clients to route through this host
net.ipv4.ip_forward = 1
SYSCTL
    sysctl -p "$SYSCTL_CONF" >/dev/null 2>&1 || true

    cat > "$NAT_CONF" << CONF
# OVNode NAT configuration (managed by install.sh)
VPN_PRIMARY_PORT=${VPN_PORT}
VPN_EXTRA_PORTS=${EXTRA_PORTS}
CONF

    cat > "$NAT_SCRIPT" << 'NAT'
#!/bin/bash
# OVNode NAT: masquerade VPN client traffic through the default uplink and
# redirect the extra VPN ports to the OpenVPN listener. Idempotent.
# Usage: ovnode-nat.sh [apply|cleanup]
set -u
CONF="/etc/default/ovnode-nat"
VPN_PRIMARY_PORT="" VPN_EXTRA_PORTS=""
# shellcheck disable=SC1090
[[ -f "$CONF" ]] && . "$CONF"

rule() {  # rule <add|del> <table> <chain> <args...>
    local op="$1" table="$2" chain="$3"; shift 3
    if [[ "$op" == "add" ]]; then
        iptables -t "$table" -C "$chain" "$@" 2>/dev/null || iptables -t "$table" -A "$chain" "$@"
    else
        iptables -t "$table" -D "$chain" "$@" 2>/dev/null || true
    fi
}

each_redirect() {  # each_redirect <add|del>
    local op="$1" port proto
    [[ -n "$VPN_PRIMARY_PORT" && -n "$VPN_EXTRA_PORTS" ]] || return 0
    for port in ${VPN_EXTRA_PORTS//,/ }; do
        for proto in tcp udp; do
            rule "$op" nat PREROUTING -p "$proto" --dport "$port" \
                -j REDIRECT --to-ports "$VPN_PRIMARY_PORT"
        done
    done
}

IFACE="$(ip route show default 2>/dev/null | awk '{print $5; exit}')"

case "${1:-apply}" in
    apply)
        if [[ -z "$IFACE" ]]; then echo "ovnode-nat: no default interface found" >&2; exit 1; fi
        rule add nat POSTROUTING -o "$IFACE" -j MASQUERADE
        each_redirect add
        ;;
    cleanup)
        [[ -n "$IFACE" ]] && rule del nat POSTROUTING -o "$IFACE" -j MASQUERADE
        each_redirect del
        ;;
    *) echo "usage: $0 [apply|cleanup]" >&2; exit 2 ;;
esac
NAT
    chmod +x "$NAT_SCRIPT"

    cat > "/etc/systemd/system/$NAT_SERVICE" << UNIT
[Unit]
Description=OVNode NAT (masquerade + VPN port redirects)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$NAT_SCRIPT apply
ExecStop=$NAT_SCRIPT cleanup

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload >/dev/null 2>&1
    systemctl enable "$NAT_SERVICE" >/dev/null 2>&1
    if systemctl restart "$NAT_SERVICE" >/dev/null 2>&1; then
        if [[ -n "$EXTRA_PORTS" ]]; then
            step "NAT + IP forwarding enabled, ports ${EXTRA_PORTS} → ${VPN_PORT}"
        else
            step "NAT + IP forwarding enabled"
        fi
    else
        warn "Could not start NAT service — VPN clients may not route traffic"
    fi
}

setup_nat() {
    if [[ "$NO_NAT" -eq 1 ]]; then info "Skipping NAT setup (--no-nat)"; return; fi
    if ! command -v iptables >/dev/null 2>&1; then
        info "Installing iptables/iproute2 for NAT..."
        pkg_install iptables iproute2
    fi
    # Some distros ship iptables-nft without a persistent service; our
    # oneshot unit re-applies the rules on every boot.
    write_nat_files
}

# ── Log rotation ───────────────────────────────────────────────────────
# server.conf uses `log-append openvpn.log`, which grows without bound and
# will eventually fill a small VPS disk (killing OpenVPN with it). The
# agent log rotates itself; the OpenVPN log needs logrotate. copytruncate
# is used because OpenVPN keeps the file descriptor open.
setup_logrotate() {
    if ! command -v logrotate >/dev/null 2>&1; then
        if [[ -n "$PKG_INSTALL" ]]; then
            pkg_install logrotate
        else
            warn "logrotate not found — install it so openvpn.log gets rotated"
        fi
    fi
    cat > "$LOGROTATE_CONF" << ROTATE
${OPENVPN_ROOT}/server/openvpn.log {
    size 10M
    rotate 3
    compress
    missingok
    notifempty
    copytruncate
}
ROTATE
    step "Log rotation configured ($LOGROTATE_CONF)"
}

# ── OpenVPN scaffolding ────────────────────────────────────────────────
ensure_openvpn_dirs() {
    mkdir -p "$OPENVPN_ROOT/server" "$OPENVPN_ROOT/ccd" \
             "$OPENVPN_ROOT/ovnode/users" "$OPENVPN_ROOT/ovnode/sessions" "$OPENVPN_ROOT/ovnode/scripts"
    # Some distros (Arch) lack the "nogroup" group that the generated
    # server.conf references — create it so OpenVPN can start.
    getent group nogroup >/dev/null 2>&1 || groupadd -r nogroup 2>/dev/null || true
    # The tun device is required; try to load the kernel module if missing.
    if [[ ! -e /dev/net/tun ]]; then
        mkdir -p /dev/net
        modprobe tun 2>/dev/null || true
        mknod /dev/net/tun c 10 200 2>/dev/null || true
        chmod 600 /dev/net/tun 2>/dev/null || true
    fi
    if [[ -e /dev/net/tun ]]; then
        step "OpenVPN directories ready ($OPENVPN_ROOT), /dev/net/tun present"
    else
        warn "/dev/net/tun is missing — OpenVPN cannot start (Docker: mount it, bare-metal: modprobe tun)"
    fi
}

start_openvpn_service() {
    # The agent generates server.conf + PKI on first boot; enable/start the
    # systemd instance that reads it.
    if has_systemd; then
        systemctl enable openvpn-server@server >/dev/null 2>&1 || true
        systemctl restart openvpn-server@server >/dev/null 2>&1 && \
            step "OpenVPN server service started" || \
            warn "Could not start openvpn-server@server — check: journalctl -u openvpn-server@server -n 50"
    elif command -v rc-service >/dev/null 2>&1; then
        rc-update add openvpn default >/dev/null 2>&1 || true
        rc-service openvpn start >/dev/null 2>&1 && step "OpenVPN started (OpenRC)" || warn "Start OpenVPN manually"
    else
        warn "No init system detected — start OpenVPN manually: openvpn --config $OPENVPN_ROOT/server/server.conf"
    fi
}

# ── Firewall ───────────────────────────────────────────────────────────
# Every VPN port is opened for BOTH protocols: the panel can switch the
# node between udp and tcp at runtime, and the extra-port redirects always
# cover both.
open_firewall_ports() {
    local vpn_all="$VPN_PORT ${EXTRA_PORTS//,/ }" p
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw allow "$PORT/tcp" >/dev/null 2>&1
        for p in $vpn_all; do
            ufw allow "$p/udp" >/dev/null 2>&1
            ufw allow "$p/tcp" >/dev/null 2>&1
        done
        step "UFW: allowed $PORT/tcp + VPN port(s) ${vpn_all// /, }"
    elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
        firewall-cmd --permanent --add-port="$PORT/tcp" >/dev/null 2>&1
        for p in $vpn_all; do
            firewall-cmd --permanent --add-port="$p/udp" >/dev/null 2>&1
            firewall-cmd --permanent --add-port="$p/tcp" >/dev/null 2>&1
        done
        firewall-cmd --reload >/dev/null 2>&1
        step "firewalld: allowed $PORT/tcp + VPN port(s) ${vpn_all// /, }"
    fi
}

# ── Systemd unit ───────────────────────────────────────────────────────
write_systemd_unit() {
    # ExecStart runs the venv interpreter directly: no uv resolution at
    # boot, one fewer process, faster restarts, lower RAM.
    cat > "/etc/systemd/system/$SYSTEMD_SERVICE" << UNIT
[Unit]
Description=OVNode OpenVPN Node Agent (${NODE_NAME})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=${APP_DIR}
Environment="PATH=${APP_DIR}/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
EnvironmentFile=${APP_DIR}/.env
ExecStart=${APP_DIR}/.venv/bin/python ${APP_DIR}/main.py
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload >/dev/null 2>&1
    systemctl enable "$SYSTEMD_SERVICE" >/dev/null 2>&1
    step "systemd unit written: /etc/systemd/system/$SYSTEMD_SERVICE"
}

wait_health() {
    local url="$1" tries="${2:-30}" i
    for i in $(seq 1 "$tries"); do
        curl -fsSk -o /dev/null --max-time 3 "$url" 2>/dev/null && return 0
        sleep 1
    done
    return 1
}

# ── Source / environment ───────────────────────────────────────────────
fetch_source() {
    if command -v git >/dev/null 2>&1; then
        git clone --depth 1 --branch "$BRANCH" "https://github.com/${REPO}.git" "$APP_DIR" >/dev/null 2>&1 &
        spinner "Cloning repository" $!
    else
        curl -sSLo /tmp/ovn.tar.gz "https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz" &
        spinner "Downloading source tarball" $!
        mkdir -p "$APP_DIR"
        tar -xzf /tmp/ovn.tar.gz --strip-components=1 -C "$APP_DIR" >/dev/null 2>&1 || die "Extract failed"
        rm -f /tmp/ovn.tar.gz
    fi
}

write_env() {
    # Note: TUNNEL_ADDRESS is intentionally NOT written here — the node's
    # pydantic Settings rejects extra env fields, and the panel pushes the
    # tunnel address via /sync/config when the node is added/updated.
    cat > "$APP_DIR/.env" << EOF
NODE_NAME=${NODE_NAME}
DATA_DIR=${DATA_BASE}/${NODE_NAME}
SERVICE_PORT=${PORT}
API_KEY=${API_KEY}
OPENVPN_PORT=${VPN_PORT}
TLS_METHOD=${TLS_METHOD}
$( if [[ -n "$EXTRA_PORTS" ]]; then echo "OVNODE_EXTRA_PORTS=${EXTRA_PORTS}"; fi )
$( if [[ "$IPV6" -eq 1 ]]; then echo "OVNODE_ENABLE_IPV6=1"; fi )
$( if [[ -n "$TLS_KEY" ]]; then echo "SSL_KEYFILE=${TLS_KEY}"; fi )
$( if [[ -n "$TLS_CERT" ]]; then echo "SSL_CERTFILE=${TLS_CERT}"; fi )
EOF
    chmod 600 "$APP_DIR/.env"
    step ".env written"
}

# ── Docker ─────────────────────────────────────────────────────────────
setup_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        info "Installing Docker Engine..."
        if [[ "$PKG_INSTALL" == apt* ]]; then
            $PKG_UPDATE >/dev/null 2>&1 || true
            $PKG_INSTALL docker.io >/dev/null 2>&1 \
                || $PKG_INSTALL docker-ce >/dev/null 2>&1 \
                || die "Could not install Docker via apt. Install manually: https://docs.docker.com/engine/install/"
        else
            pkg_install docker docker-compose-plugin >/dev/null 2>&1 || pkg_install docker
        fi
        command -v docker >/dev/null 2>&1 || die "Docker binary not found"
    fi
    docker compose version >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1 \
        || die "Docker Compose v2 is required (docker compose plugin)"

    local compose="$DATA_BASE/$NODE_NAME/docker-compose.yml"
    mkdir -p "$DATA_BASE/$NODE_NAME"
    cat > "$compose" << COMPOSE
services:
  ovnode:
    build:
      context: ${APP_DIR}
      dockerfile: Dockerfile
    container_name: ovnode-${NODE_NAME}
    restart: unless-stopped
    network_mode: host
    environment:
      SERVICE_PORT: ${PORT}
      API_KEY: ${API_KEY}
      OPENVPN_PORT: ${VPN_PORT}
      TLS_METHOD: ${TLS_METHOD}
      OVNODE_OPENVPN_ROOT: /etc/openvpn
$( if [[ -n "$EXTRA_PORTS" ]]; then echo "      OVNODE_EXTRA_PORTS: \"${EXTRA_PORTS}\""; fi )
$( if [[ "$IPV6" -eq 1 ]]; then echo "      OVNODE_ENABLE_IPV6: 1"; fi )
$( [[ -n "$TLS_KEY" ]] && echo "      SSL_KEYFILE: ${TLS_KEY}" )
$( [[ -n "$TLS_CERT" ]] && echo "      SSL_CERTFILE: ${TLS_CERT}" )
    volumes:
      - ${OPENVPN_ROOT}:/etc/openvpn
      - ${DATA_BASE}/${NODE_NAME}:/app/data
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    logging:
      options:
        max-size: "1m"
        max-file: "3"
COMPOSE
    # The compose file embeds the API key — keep it root-only, like .env.
    chmod 600 "$compose"

    info "Building and starting Docker container (first build takes a while)..."
    ( cd "$APP_DIR" && docker compose -f "$compose" up -d --build ) >/dev/null 2>&1 &
    spinner "Docker container started" $!
}

# ── Install ────────────────────────────────────────────────────────────
do_install() {
    if [[ -d "$APP_DIR" ]]; then die "Already installed ($APP_DIR exists). Use 'uninstall' first."; fi
    mkdir -p "$DATA_BASE/$NODE_NAME"

    sep; info "Downloading OVNode ($BRANCH)..."
    fetch_source

    info "Installing Python dependencies (uv sync)..."
    cd "$APP_DIR"
    uv_sync &
    spinner "Python packages installed" $!

    setup_tls
    write_env

    local scheme="http"
    if [[ "$TLS_METHOD" != "none" ]]; then scheme="https"; fi
    local host; host="$(hostname -I 2>/dev/null | awk '{print $1}')"

    if [[ "$DOCKER" -eq 1 ]]; then
        setup_docker
    else
        if ! has_systemd; then
            warn "systemd not found — start the agent manually: cd $APP_DIR && .venv/bin/python main.py"
        else
            write_systemd_unit
            systemctl restart "$SYSTEMD_SERVICE" >/dev/null 2>&1 &
            spinner "Node agent service started" $!
        fi
    fi

    # First boot generates the PKI + server.conf; wait for the agent to
    # answer /sync/health before bringing up OpenVPN so the config exists.
    if ! wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 45; then
        warn "Agent did not answer /sync/health — check: journalctl -u $SYSTEMD_SERVICE -n 50"
    fi

    ensure_openvpn_dirs
    # In Docker the OpenVPN server runs inside the container — only manage
    # it on the host for native installs.
    if [[ "$DOCKER" -eq 0 ]]; then start_openvpn_service; fi
    setup_nat
    setup_logrotate
    open_firewall_ports

    sep; line ""
    step "${B}Installation complete!${NC}"
    line ""
    field "Node name"   "$NODE_NAME"
    field "Service"     "${WH}${scheme}://${host}:${PORT}${NC}"
    field "OpenVPN"     "$(vpn_ports_label)"
    field "API key"     "${GR}${API_KEY}${NC}"
    field "Data"        "$DATA_BASE/$NODE_NAME"
    field "OpenVPN cfg" "$OPENVPN_ROOT/server"
    line ""
    info "Add this node to your panel:"
    info "  Panel → Nodes → Add Node → address ${host}, port ${PORT},"
    info "  API key ${API_KEY} → save."
    if [[ -n "$EXTRA_PORTS" ]]; then
        info "Clients will receive all VPN ports (${VPN_PORT},${EXTRA_PORTS}) in their .ovpn"
        info "and automatically fail over if one is blocked."
    fi
    line ""
}

# ── Update ─────────────────────────────────────────────────────────────
do_update() {
    [[ -d "$APP_DIR" ]] || die "Not installed ($APP_DIR missing)"
    # Recover install parameters from the installed .env when not passed on
    # the CLI, so `update` never silently changes the configuration.
    local env_get; env_get() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"'; }
    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(env_get NODE_NAME)"
    : "${NODE_NAME:=node-1}"
    [[ -n "$PORT" ]] || PORT="$(env_get SERVICE_PORT)"
    : "${PORT:=$DEFAULT_PORT}"
    if [[ -z "$VPN_PORTS" ]]; then
        VPN_PORT="$(env_get OPENVPN_PORT)"; : "${VPN_PORT:=$DEFAULT_VPN}"
        EXTRA_PORTS="$(env_get OVNODE_EXTRA_PORTS)"
    else
        parse_vpn_ports
    fi
    [[ "$TLS_METHOD" != "none" ]] || TLS_METHOD="$(env_get TLS_METHOD)"
    : "${TLS_METHOD:=none}"

    line ""; info "Updating OVNode..."
    detect_os
    # Auto-detect the deployment mode: a compose file means this install was
    # done with --docker, even when `update` is called without the flag.
    if [[ -f "$DATA_BASE/$NODE_NAME/docker-compose.yml" ]]; then
        DOCKER=1
        info "Detected Docker deployment (compose file present)"
    fi
    ensure_uv
    backup_dir "$DATA_BASE" "node"
    backup_dir "$OPENVPN_ROOT/server/pki" "node-pki"

    cd "$APP_DIR"
    if [[ -d .git ]]; then
        git stash --quiet 2>/dev/null || true
        git pull --rebase origin "$BRANCH" 2>&1 &
        spinner "Pulling latest changes" $!
        git stash pop --quiet 2>/dev/null || true
    else
        warn "No git checkout — re-downloading source over existing install (.env preserved)"
        curl -sSLo /tmp/ovn.tar.gz "https://github.com/${REPO}/archive/refs/heads/${BRANCH}.tar.gz" &
        spinner "Downloading source" $!
        tar -xzf /tmp/ovn.tar.gz --strip-components=1 -C "$APP_DIR" >/dev/null 2>&1 || die "Extract failed"
        rm -f /tmp/ovn.tar.gz
    fi

    uv_sync &
    spinner "Updating Python dependencies" $!

    local scheme="http"
    if [[ "$TLS_METHOD" != "none" ]]; then scheme="https"; fi
    if [[ "$DOCKER" -eq 1 ]]; then
        ( cd "$APP_DIR" && docker compose -f "$DATA_BASE/$NODE_NAME/docker-compose.yml" up -d --build ) >/dev/null 2>&1 &
        spinner "Recreating Docker container" $!
    else
        # Re-write the unit: older installs launched via `uv run`.
        has_systemd && write_systemd_unit
        systemctl restart "$SYSTEMD_SERVICE" >/dev/null 2>&1 &
        spinner "Node agent restarted" $!
    fi
    setup_nat
    setup_logrotate
    wait_health "${scheme}://127.0.0.1:${PORT}/sync/health" 30 \
        || warn "Agent did not answer /sync/health after update — check: journalctl -u $SYSTEMD_SERVICE -n 50"
    step "Update complete"
    line ""
}

# ── Uninstall ──────────────────────────────────────────────────────────
do_uninstall() {
    [[ -d "$APP_DIR" ]] || die "Not installed ($APP_DIR missing)"
    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(grep -E '^NODE_NAME=' "$APP_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true)"
    : "${NODE_NAME:=node-1}"
    confirm "Remove OVNode and stop all services?" || die "Cancelled."

    # Stopping the NAT unit runs its ExecStop cleanup (rules removed).
    systemctl stop "$SYSTEMD_SERVICE" "$NAT_SERVICE" openvpn-server@server 2>/dev/null || true
    systemctl disable "$SYSTEMD_SERVICE" "$NAT_SERVICE" openvpn-server@server 2>/dev/null || true
    rm -f "/etc/systemd/system/$SYSTEMD_SERVICE" "/etc/systemd/system/$NAT_SERVICE"
    systemctl daemon-reload 2>/dev/null || true

    if command -v docker >/dev/null 2>&1 && [[ -f "$DATA_BASE/$NODE_NAME/docker-compose.yml" ]]; then
        ( cd "$APP_DIR" && docker compose -f "$DATA_BASE/$NODE_NAME/docker-compose.yml" down ) >/dev/null 2>&1 || true
        docker rm -f "ovnode-$NODE_NAME" >/dev/null 2>&1 || true
    fi

    rm -f "$NAT_SCRIPT" "$NAT_CONF" "$SYSCTL_CONF" "$LOGROTATE_CONF"
    rm -rf "$APP_DIR"
    if [[ "$PURGE" -eq 1 ]]; then
        backup_dir "$DATA_BASE" "node-pre-purge"
        rm -rf "$DATA_BASE"
        backup_dir "$OPENVPN_ROOT" "openvpn-pre-purge"
        rm -rf "$OPENVPN_ROOT"
        step "Data and OpenVPN configuration removed"
    else
        step "App removed. Data kept at $DATA_BASE and $OPENVPN_ROOT (use --purge to remove them too)"
    fi
    step "OVNode uninstalled"
    line ""
}

# ── Interactive setup ──────────────────────────────────────────────────
interactive_setup() {
    local api_default
    api_default="$(openssl rand -hex 32)"
    NODE_NAME="$(ask "Node name" "node-1")"
    PORT="$(ask "Service port" "$(find_free_port "$DEFAULT_PORT")")"
    VPN_PORTS="$(ask "OpenVPN port(s), comma sep." "$DEFAULT_VPN")"
    API_KEY="$(ask "API key (blank=generate)" "$api_default")"

    sep; line "  TLS:"
    line "  ${WH}1${NC})  Let's Encrypt (domain)      ${WH}2${NC})  Let's Encrypt (IP)"
    line "  ${WH}3${NC})  Self-signed                 ${WH}4${NC})  Custom cert path"
    line "  ${WH}5${NC})  None (HTTP)"
    local tls_choice
    tls_choice="$(ask "TLS mode" "5")"
    case "${tls_choice:-5}" in
        1) TLS_METHOD="letsencrypt"; TLS_DOMAIN="$(ask "Domain" "")"; [[ -n "$TLS_DOMAIN" ]] || die "Domain required for Let's Encrypt" ;;
        2) TLS_METHOD="letsencrypt-ip"; TLS_DOMAIN="$(hostname -I 2>/dev/null | awk '{print $1}')" ;;
        3) TLS_METHOD="selfsigned" ;;
        4) TLS_METHOD="custom"; TLS_KEY="$(ask "Key file" "")"; TLS_CERT="$(ask "Cert file" "")" ;;
        *) TLS_METHOD="none" ;;
    esac
}

# ── Preconditions ──────────────────────────────────────────────────────
check_root() { [[ "$EUID" -eq 0 ]] || die "Must run as root."; }

check_deps() {
    local missing=() cmd
    for cmd in curl tar openssl git python3; do
        command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
    done
    [[ ${#missing[@]} -eq 0 ]] || pkg_install "${missing[@]}"
    if ! command -v openvpn >/dev/null 2>&1; then
        info "Installing OpenVPN + easy-rsa (for client PKI)..."
        pkg_install openvpn easy-rsa
    fi
    step "System dependencies present"
}

# ── Main ───────────────────────────────────────────────────────────────
main() {
    parse_args "$@"
    command clear >/dev/null 2>&1 || true
    line ""
    line "  ${B}OVNode${NC} — OpenVPN Node Agent Installer ${GY}v${VERSION}${NC}"
    sep; line ""

    case "$ACTION" in
        uninstall) do_uninstall; exit 0 ;;
        update)    [[ "$YES" -eq 1 ]] || confirm "Update OVNode now?" || exit 0; do_update; exit 0 ;;
    esac

    if [[ -d "$APP_DIR" ]]; then
        warn "OVNode is already installed"
        if is_tty; then
            line ""
            line "  ${GR}1${NC})  Update to latest version"
            line "  ${YL}2${NC})  Uninstall"
            line "  ${GY}3${NC})  Quit"
            line ""
            local choice; choice="$(ask "Select" "1")"
            case "${choice:-1}" in
                1) do_update ;;
                2) do_uninstall ;;
                *) exit 0 ;;
            esac
        else
            info "Already installed — run with 'update' to refresh it."
        fi
        exit 0
    fi

    detect_os
    if [[ "$YES" -eq 0 && ( -z "$PORT" || -z "$API_KEY" ) ]]; then
        interactive_setup
    else
        : "${PORT:=$(find_free_port "$DEFAULT_PORT")}"
        : "${VPN_PORTS:=$DEFAULT_VPN}"
        : "${NODE_NAME:=node-1}"
        : "${TLS_METHOD:=none}"
        [[ -n "$API_KEY" ]] || API_KEY="$(openssl rand -hex 32)"
    fi
    validate_input

    field "OS"        "$OS_NAME"
    field "Mode"      "$([ $DOCKER -eq 1 ] && echo Docker || echo Native)"
    field "Node"      "$NODE_NAME"
    field "Service"   "$PORT"
    field "OpenVPN"   "$(vpn_ports_label)"
    field "TLS"       "$TLS_METHOD"
    field "Install"   "$APP_DIR"
    field "Data"      "$DATA_BASE/$NODE_NAME"
    if [[ "$TLS_METHOD" == "none" ]]; then
        warn "TLS is DISABLED — the API key is a bearer secret sent in plaintext."
        warn "For internet exposure use --tls letsencrypt/selfsigned; for LAN-only use a private network."
    fi
    sep
    confirm "Proceed with installation?" || die "Cancelled."

    check_root
    check_deps
    ensure_uv
    do_install
}

main "$@"
