# Copyright (c) 2026 anonysec
# SPDX-License-Identifier: MIT

"""easy-rsa invocation, its lock file, and the PKI directory tree."""

import os
import shutil
import subprocess

from core.logger import logger
from core.openvpn.atomic import file_lock
from core.openvpn.pki import node as _node
from core.openvpn.pki import paths as _paths


def run_easyrsa(*args: str, timeout: int = 120, pki_dir: str | None = None) -> bool:
    """Run easyrsa in batch mode. Returns True on success.

    Serialized with a lock file: parallel create/revoke calls corrupt
    index.txt otherwise (easyrsa has no internal locking).
    """
    easyrsa_bin = os.path.join(_paths.EASYRSA_DIR, "easyrsa")
    if not os.path.exists(easyrsa_bin):
        logger.error("easyrsa not found at %s", easyrsa_bin)
        return False
    lock_path = os.path.join(pki_dir or _paths.PKI_DIR, ".easyrsa.lock")
    with file_lock(lock_path) as lock_err:
        if lock_err is not None:
            logger.error("easyrsa lock unavailable (%s) — refusing to run unlocked", lock_err)
            return False
        try:
            cmd = [easyrsa_bin, f"--pki-dir={pki_dir or _paths.PKI_DIR}"] + list(args)
            # Minimal env: don't leak API_KEY / panel secrets to the child.
            minimal_env = {
                "PATH": os.environ.get("PATH", "/usr/sbin:/usr/bin:/sbin:/bin"),
                "EASYRSA_BATCH": "1",
                "HOME": os.environ.get("HOME", "/root"),
            }
            subprocess.run(
                cmd,
                cwd=_paths.EASYRSA_DIR,
                env=minimal_env,
                check=True,
                capture_output=True,
                timeout=timeout,
            )
            return True
        except subprocess.CalledProcessError as e:
            logger.error(
                "easyrsa %s failed (rc=%d): %s",
                " ".join(args),
                e.returncode,
                e.stderr[-500:].decode() if e.stderr else str(e),
            )
            return False
        except subprocess.TimeoutExpired:
            logger.error("easyrsa %s timed out after %ds", " ".join(args), timeout)
            return False
        except Exception as e:
            logger.error("easyrsa %s error: %s", " ".join(args), e)
            return False


_easyrsa = run_easyrsa


# ── easy-rsa bootstrap ───────────────────────────────────────────────


def _setup_easyrsa() -> None:
    """Copy easy-rsa into place and write a modern vars file (fresh only)."""
    if os.path.exists(_paths.EASYRSA_DIR) and os.path.exists(
        os.path.join(_paths.EASYRSA_DIR, "easyrsa")
    ):
        _write_easyrsa_vars()
        return
    os.makedirs(_paths.EASYRSA_DIR, exist_ok=True)
    src = "/usr/share/easy-rsa"
    if os.path.exists(src):
        shutil.copytree(src, _paths.EASYRSA_DIR, dirs_exist_ok=True)
        os.chmod(os.path.join(_paths.EASYRSA_DIR, "easyrsa"), 0o755)
    _write_easyrsa_vars()


def _write_easyrsa_vars() -> None:
    """Write easy-rsa defaults when a vars file does not exist yet.

    Fresh PKI uses ECDSA (prime256v1): ~2-3x faster signs than secp384r1 with
    smaller certs. Existing installs keep their vars file, so an existing
    secp384r1/RSA PKI is never disrupted.

    EASYRSA_REQ_CN is intentionally omitted: when set, easy-rsa refuses
    `build-server-full <name>` / `build-client-full <name>` with "Option
    conflict: ... does not support setting an external commonName" — it is
    only valid for `build-ca`. The per-cert CN is passed positionally.
    """
    vars_path = os.path.join(_paths.EASYRSA_DIR, "vars")
    if os.path.exists(vars_path):
        return
    try:
        with open(vars_path, "w", encoding="utf-8") as f:
            f.write(
                "# Generated by OVNode — ECDSA defaults (safe to edit)\n"
                'set_var EASYRSA_ALGO "ec"\n'
                'set_var EASYRSA_CURVE "prime256v1"\n'
                'set_var EASYRSA_BATCH "1"\n'
                'set_var EASYRSA_NO_PASS "1"\n'
                'set_var EASYRSA_CA_EXPIRE "3650"\n'
                'set_var EASYRSA_CERT_EXPIRE "1825"\n'
                'set_var EASYRSA_CRL_DAYS "365"\n'
                # EASYRSA_REQ_CN is intentionally unset: easy-rsa only allows it
                # for `build-ca`. Each server/client cert sets its CN positionally.
            )
        logger.info("Wrote easy-rsa vars file (%s)", vars_path)
    except OSError as e:
        logger.error("Could not write easy-rsa vars: %s", e)


def _ensure_dir_tree() -> None:
    """Create all PKI subdirectories + index files needed by easy-rsa."""
    subdirs = [
        "private",
        "issued",
        "reqs",
        "certs_by_serial",
        "index.txt.attrs",
        "inline/private",
        "revoked/certs_by_serial",
        "revoked/private",
        "revoked/reqs",
        "revoked/issued",
    ]
    for subdir in subdirs:
        os.makedirs(os.path.join(_paths.PKI_DIR, subdir), exist_ok=True)
    for fname in [
        "index.txt",
        "index.txt.attr",
        "serial",
        "serial.old",
        "crlnumber",
        "crlnumber.old",
    ]:
        path = os.path.join(_paths.PKI_DIR, fname)
        if not os.path.exists(path):
            with open(path, "w") as f:
                if fname in ("serial", "crlnumber"):
                    f.write("1000\n")


def _gen_tls_key() -> None:
    """Generate the tls-crypt pre-shared key (idempotent)."""
    if os.path.exists(_paths.TLS_KEY):
        os.chmod(_paths.TLS_KEY, 0o600)
        return
    try:
        subprocess.run(
            [_node._openvpn_bin(), "--genkey", "secret", _paths.TLS_KEY],
            check=True,
            capture_output=True,
            timeout=60,
        )
    except FileNotFoundError:
        raise RuntimeError("openvpn binary missing — cannot generate tls-crypt key") from None
    os.chmod(_paths.TLS_KEY, 0o600)
    logger.info("TLS-crypt key generated: %s", _paths.TLS_KEY)
